# Generated by Django 5.1.15 on 2026-06-08 22:12

from django.db import migrations, models


def confirm_staff_and_superusers(apps, schema_editor):
    """Auto-confirm email for staff/superuser accounts created outside the normal signup flow."""
    UserProfile = apps.get_model("accounts", "UserProfile")
    User = apps.get_model("auth", "User")
    for user in User.objects.filter(models.Q(is_staff=True) | models.Q(is_superuser=True)):
        profile, _ = UserProfile.objects.get_or_create(user=user)
        if not profile.email_confirmed:
            profile.email_confirmed = True
            profile.email_confirmation_token = None
            profile.email_confirmation_token_expires_at = None
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password_reset_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(confirm_staff_and_superusers, migrations.RunPython.noop),
    ]
