# Generated by Django 5.1.15 on 2026-06-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_password_reset_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("nl", "Dutch")],
                default="en",
                help_text="User's preferred UI language.",
                max_length=10,
            ),
        ),
    ]
