# Generated by Django 5.1.15 on 2026-06-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('checks', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('raw_text', models.TextField()),
                ('parsed_json', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='en', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skills_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('keyword_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('title_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('other_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryJobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('parsed_json', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
