# Generated by Django 5.1.15 on 2026-06-21 23:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('international', 'International')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='international_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='local_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10),
        ),
    ]
