# Generated by Django 5.1.15 on 2026-06-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_order_delivery_zone_shopsettings_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('international', 'International')], default='', max_length=30, null=True),
        ),
    ]
