# Generated by Django 5.1.15 on 2026-06-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_delivery_zone_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
