# Generated by Django 5.1.15 on 2026-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_ordercancellationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="external_image_url",
            field=models.URLField(
                blank=True,
                help_text="Fallback image URL (e.g. Unsplash CDN) used when no uploaded image is present.",
                max_length=500,
            ),
        ),
    ]
