# Generated by Django 5.1.15 on 2026-07-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_shop_cloudinary_images_and_gallery_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="seller_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OrderEmailLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("buyer_confirmation", "Buyer confirmation"),
                            ("seller_notification", "Seller notification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="email_logs", to="marketplace.order"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["order", "email_type"], name="marketplace_order_i_ab4d3c_idx"),
                    models.Index(fields=["status"], name="marketplace_status_dd9ca7_idx"),
                ],
            },
        ),
    ]
