# Generated by Django 5.1.15 on 2026-07-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_order_buyer_email_sent_at_order_seller_email_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="country",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="shop",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="shop",
            name="opening_hours",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="shop",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="shop",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="shop",
            name="shop_type",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="shop",
            name="short_description",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="shop",
            name="social_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="shop",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="cancellation_request_email_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="low_stock_notification_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="new_order_email_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="supported_delivery_countries",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
