# Generated by Django 5.1.15 on 2026-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_add_shop_configuration_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfillment_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pickup_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pickup_address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pickup_address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pickup_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pickup_country",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pickup_postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="whatsapp_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="whatsapp_group_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
