# Generated by Django 5.1.15 on 2026-10-01 19:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_order_fulfillment_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_slot_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_slot_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordering_rules_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='physical_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selling_unit',
            field=models.CharField(blank=True, choices=[('PIECE', 'Piece'), ('PACK', 'Pack'), ('PLATE', 'Plate'), ('BOX', 'Box'), ('TRAY', 'Tray'), ('BOTTLE', 'Bottle'), ('WEIGHT', 'Weight / volume')], max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_weight_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='units_per_pack',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('GRAM', 'Gram'), ('KILOGRAM', 'Kilogram'), ('MILLILITRE', 'Millilitre'), ('LITRE', 'Litre')], max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount that must be spent on this product.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of selling units.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_physical_units',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum physical pieces (selling units × pieces per pack).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_unit',
            field=models.CharField(choices=[('PIECE', 'Piece'), ('PACK', 'Pack'), ('PLATE', 'Plate'), ('BOX', 'Box'), ('TRAY', 'Tray'), ('BOTTLE', 'Bottle'), ('WEIGHT', 'Weight / volume')], default='PIECE', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_pack',
            field=models.PositiveIntegerField(blank=True, help_text='Physical pieces contained in one selling unit (e.g. 2 pieces per pack).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('GRAM', 'Gram'), ('KILOGRAM', 'Kilogram'), ('MILLILITRE', 'Millilitre'), ('LITRE', 'Litre')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight or volume of one selling unit.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='pickup_booking_window_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='How many days ahead (after preparation time) buyers can choose a pickup slot.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='pickup_slot_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Length of each selectable pickup slot in minutes.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='pickup_timezone',
            field=models.CharField(default='Europe/Amsterdam', help_text='IANA timezone used for opening hours and pickup slots.', max_length=64),
        ),
    ]
