# Generated by Django 5.1.15 on 2026-10-05 20:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_configure_product_selling_formats"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="whatsapp_notifications_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OrderWhatsAppNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recipient",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter an international phone number in E.164 format, e.g. +31612345678.",
                                regex="^\\+[1-9][0-9]{7,14}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Accepted by provider"),
                            ("failed", "Failed"),
                            ("unknown", "Delivery uncertain; do not resend automatically"),
                            ("skipped", "Disabled or recipient changed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_notification",
                        to="marketplace.order",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["status", "next_attempt_at"], name="marketplace_wa_due_idx")],
            },
        ),
    ]
