# Generated by Django 5.1.15 on 2026-10-07 19:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_configure_product_selling_formats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="vat_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional percentage override; blank uses the shop default. Price is VAT-inclusive.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="billing_address_line1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="billing_address_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="billing_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="billing_country",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="billing_postcode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="default_vat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Configured percentage, not a tax determination. All catalogue prices include VAT.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="invoice_footer",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="invoice_iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="invoice_prefix",
            field=models.CharField(
                blank=True,
                help_text="Blank uses SHOP followed by the shop ID. Numbers also include the shop ID to avoid collisions.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9][A-Z0-9-]{0,19}$", "Use 1-20 uppercase letters, digits or hyphens."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="kvk_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="legal_business_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="vat_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("invoice_number", models.CharField(max_length=80, unique=True)),
                ("status", models.CharField(default="issued", editable=False, max_length=20)),
                ("issue_date", models.DateField()),
                ("order_number", models.CharField(max_length=30)),
                ("order_date", models.DateTimeField()),
                ("currency", models.CharField(max_length=10)),
                ("subtotal_ex_vat", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vat_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_inc_vat", models.DecimalField(decimal_places=2, max_digits=12)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("delivery_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("seller_snapshot", models.JSONField()),
                ("customer_snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="marketplace.order"
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="marketplace.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["issue_date", "invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=80)),
                ("kind", models.CharField(default="product", max_length=20)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price_inc_vat", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vat_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("unit_price_ex_vat", models.DecimalField(decimal_places=6, max_digits=12)),
                ("discount_inc_vat", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("line_total_ex_vat", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vat_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("line_total_inc_vat", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="items", to="marketplace.invoice"
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="marketplace.orderitem"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePDF",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="document", to="marketplace.invoice"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="marketplace.shop")),
            ],
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(fields=("order", "shop"), name="unique_invoice_order_shop"),
        ),
        migrations.AddConstraint(
            model_name="invoicesequence",
            constraint=models.UniqueConstraint(fields=("shop", "year"), name="unique_invoice_sequence_shop_year"),
        ),
    ]
