# Generated by Django 5.1.15 on 2026-10-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0015_seed_seller_billing_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="language",
            field=models.CharField(choices=[("en", "English"), ("nl", "Dutch")], default="en", max_length=2),
        ),
        migrations.AddField(
            model_name="product",
            name="translations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="shop",
            name="translations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="translations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
