# Generated by Django 5.1.15 on 2026-05-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_explainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancesession',
            name='status',
            field=models.CharField(choices=[('ins_pending', 'Pending'), ('ins_processing', 'Processing'), ('ins_completed', 'Completed'), ('ins_failed', 'Failed')], default='ins_pending', max_length=20),
        ),
    ]
