# Generated by Django 5.1.15 on 2026-05-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_x', '0003_alter_document_options_document_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
