# Generated by Django 5.1.15 on 2026-05-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc_x", "0004_documentfile_add_file_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="storage_backend",
            field=models.CharField(
                choices=[("s3", "S3"), ("local", "Local"), ("db", "Database")], default="db", max_length=20
            ),
        ),
    ]
