# Generated by Django 5.1.15 on 2026-06-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_personaldetail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='include_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='template_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
