# Generated by Django 5.1.15 on 2026-06-11 11:50

import re

from django.db import migrations, models


def normalize(value):
    return re.sub(r"\s+", " ", (value or "").strip()).casefold()


def populate_duplicate_keys(apps, schema_editor):
    definitions = [
        ("Skill", "normalized_name", lambda item: normalize(item.name)),
        (
            "Education",
            "duplicate_key",
            lambda item: "|".join(
                [
                    normalize(item.institution),
                    normalize(item.degree),
                    normalize(item.field_of_study),
                    str(item.start_date or ""),
                ]
            ),
        ),
        (
            "WorkExperience",
            "duplicate_key",
            lambda item: "|".join(
                [normalize(item.employer), normalize(item.job_title), str(item.start_date or "")]
            ),
        ),
        ("Project", "duplicate_key", lambda item: "|".join([normalize(item.name), normalize(item.role)])),
    ]
    for model_name, field_name, key_builder in definitions:
        model = apps.get_model("resumes", model_name)
        seen = set()
        for item in model.objects.order_by("resume_id", "id"):
            key = key_builder(item)
            scoped_key = (item.resume_id, key)
            if scoped_key in seen:
                if field_name == "normalized_name":
                    key = f"{key[:90]}|legacy-{item.pk}"
                else:
                    key = f"{key}|legacy-{item.pk}"
            else:
                seen.add(scoped_key)
            setattr(item, field_name, key)
            item.save(update_fields=[field_name])


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_include_photo_resume_template_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='duplicate_key',
            field=models.CharField(blank=True, editable=False, max_length=700),
        ),
        migrations.AddField(
            model_name='project',
            name='duplicate_key',
            field=models.CharField(blank=True, editable=False, max_length=400),
        ),
        migrations.AddField(
            model_name='skill',
            name='normalized_name',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='duplicate_key',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.RunPython(populate_duplicate_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(fields=('resume', 'duplicate_key'), name='unique_resume_education'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('resume', 'duplicate_key'), name='unique_resume_project'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('resume', 'normalized_name'), name='unique_resume_skill'),
        ),
        migrations.AddConstraint(
            model_name='workexperience',
            constraint=models.UniqueConstraint(fields=('resume', 'duplicate_key'), name='unique_resume_experience'),
        ),
    ]
