# Generated by Django 5.1.15 on 2026-06-11 16:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_alter_resume_locale_optimizedresume_output_language'),
        ('templates_app', '0005_seed_resume_template_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousResumeIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('fingerprint_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='max_edit_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='source',
            field=models.CharField(choices=[('anonymous', 'Anonymous'), ('registered', 'Registered')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='optimizedresume',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimizedresume_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumeupload_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporarygeneratedresume',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporarygeneratedresume_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporaryresumeupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temporaryresumeupload_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='optimizedresume',
            name='anonymous_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.anonymousresumeidentity'),
        ),
        migrations.AddField(
            model_name='resume',
            name='anonymous_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='resumes.anonymousresumeidentity'),
        ),
        migrations.AddField(
            model_name='resumeupload',
            name='anonymous_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='resumes.anonymousresumeidentity'),
        ),
        migrations.AddField(
            model_name='temporarygeneratedresume',
            name='anonymous_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.anonymousresumeidentity'),
        ),
        migrations.AddField(
            model_name='temporaryresumeupload',
            name='anonymous_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.anonymousresumeidentity'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anonymous_identity__isnull', True), ('user__isnull', False)), models.Q(('anonymous_identity__isnull', False), ('user__isnull', True)), _connector='OR'), name='resume_has_exactly_one_owner'),
        ),
    ]
