# Generated by Django 5.1.15 on 2026-06-12 17:57

import apps.speaking_buddy.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyPracticeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('other', 'Other')], default='en', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=30)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('prompt_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuddyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buddy_name', models.CharField(default='GuideWisey Buddy', max_length=120)),
                ('native_language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('other', 'Other')], default='en', max_length=20)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('other', 'Other')], default='en', max_length=20)),
                ('speaking_level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=30)),
                ('learning_goal', models.CharField(blank=True, max_length=255)),
                ('favorite_topics', models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ('weak_areas', models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ('preferred_correction_style', models.CharField(default='normal', max_length=40)),
                ('is_memory_enabled', models.BooleanField(default=True)),
                ('previous_conversation_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_buddy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuddyAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_type', models.CharField(choices=[('default', 'Default'), ('uploaded', 'Uploaded')], default='default', max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='speaking_buddy/avatars/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='speaking_buddy.buddyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BuddySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('other', 'Other')], default='en', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('transcript', models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ('ai_summary', models.TextField(blank=True)),
                ('user_summary', models.TextField(blank=True)),
                ('mistakes_detected', models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ('vocabulary_practiced', models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ('improvement_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='speaking_buddy.buddyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BuddyMistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(blank=True)),
                ('corrected_text', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('mistake_type', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('other', 'Other')], default='en', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='speaking_buddy.buddyprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistakes', to='speaking_buddy.buddysession')),
            ],
        ),
        migrations.CreateModel(
            name='BuddyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('text', models.TextField()),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=apps.speaking_buddy.models.default_dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='speaking_buddy.buddysession')),
            ],
        ),
        migrations.CreateModel(
            name='BuddySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(choices=[('friendly', 'Friendly'), ('teacher', 'Teacher'), ('interviewer', 'Interviewer'), ('strict_coach', 'Strict Coach'), ('casual_friend', 'Casual Friend')], default='friendly', max_length=40)),
                ('voice_style', models.CharField(choices=[('warm', 'Warm'), ('clear', 'Clear'), ('calm', 'Calm'), ('energetic', 'Energetic')], default='warm', max_length=40)),
                ('voice_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('voice_age', models.CharField(choices=[('young', 'Young'), ('adult', 'Adult'), ('senior', 'Senior')], default='adult', max_length=20)),
                ('speaking_speed', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(120)])),
                ('correction_level', models.CharField(choices=[('none', 'None'), ('light', 'Light'), ('normal', 'Normal'), ('strict', 'Strict')], default='normal', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('theme_color', models.CharField(default='#7c3aed', max_length=24)),
                ('default_topic', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_settings', to='speaking_buddy.buddyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BuddyMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('summary', 'Summary'), ('weak_area', 'Weak Area'), ('vocabulary', 'Vocabulary'), ('topic', 'Topic'), ('correction_style', 'Correction Style'), ('note', 'Note')], default='note', max_length=40)),
                ('key', models.CharField(max_length=120)),
                ('value', models.JSONField(blank=True, default=apps.speaking_buddy.models.default_dict)),
                ('importance', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='speaking_buddy.buddyprofile')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_entries', to='speaking_buddy.buddysession')),
            ],
            options={
                'unique_together': {('profile', 'memory_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='BuddyVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120)),
                ('translation', models.CharField(blank=True, max_length=255)),
                ('example_sentence', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('other', 'Other')], default='en', max_length=20)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='speaking_buddy.buddyprofile')),
            ],
            options={
                'unique_together': {('profile', 'word', 'language')},
            },
        ),
    ]
