# Generated by Django 5.1.15 on 2026-06-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking_buddy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddymistake",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("nl", "Dutch"),
                    ("hi", "Hindi"),
                    ("ur", "Urdu"),
                    ("ar", "Arabic"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("other", "Other"),
                ],
                default="en",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="buddypracticetopic",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("nl", "Dutch"),
                    ("hi", "Hindi"),
                    ("ur", "Urdu"),
                    ("ar", "Arabic"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("other", "Other"),
                ],
                default="en",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="buddyprofile",
            name="native_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("nl", "Dutch"),
                    ("hi", "Hindi"),
                    ("ur", "Urdu"),
                    ("ar", "Arabic"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("other", "Other"),
                ],
                default="en",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="buddyprofile",
            name="target_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("nl", "Dutch"),
                    ("hi", "Hindi"),
                    ("ur", "Urdu"),
                    ("ar", "Arabic"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("other", "Other"),
                ],
                default="en",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="buddysession",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("nl", "Dutch"),
                    ("hi", "Hindi"),
                    ("ur", "Urdu"),
                    ("ar", "Arabic"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("other", "Other"),
                ],
                default="en",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="buddyvocabulary",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("nl", "Dutch"),
                    ("hi", "Hindi"),
                    ("ur", "Urdu"),
                    ("ar", "Arabic"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("other", "Other"),
                ],
                default="en",
                max_length=20,
            ),
        ),
    ]
