# Generated by Django 5.1.15 on 2026-06-12 22:30

from urllib.parse import quote

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def svg_data_uri(label, accent, secondary):
    svg = f"""
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
      <defs>
        <radialGradient id="g" cx="50%" cy="35%" r="75%">
          <stop offset="0%" stop-color="{accent}" stop-opacity="0.9"/>
          <stop offset="100%" stop-color="{secondary}" stop-opacity="0.9"/>
        </radialGradient>
      </defs>
      <rect width="512" height="512" rx="256" fill="url(#g)"/>
      <circle cx="256" cy="242" r="140" fill="#0f172a" opacity="0.92"/>
      <circle cx="210" cy="222" r="34" fill="#e0f2fe"/>
      <circle cx="302" cy="222" r="34" fill="#e0f2fe"/>
      <circle cx="210" cy="222" r="14" fill="#0f172a"/>
      <circle cx="302" cy="222" r="14" fill="#0f172a"/>
      <rect x="176" y="292" width="160" height="86" rx="34" fill="#111827"/>
      <path d="M192 300h128v18c0 24-18 42-64 42s-64-18-64-42v-18z" fill="#f8fafc"/>
      <path d="M198 336c13 16 29 24 58 24s45-8 58-24c-9 20-24 34-58 34s-49-14-58-34z" fill="#fb7185"/>
      <text x="256" y="460" text-anchor="middle" font-size="44" font-family="Arial, sans-serif" fill="#ffffff">{label}</text>
    </svg>
    """.strip()
    return "data:image/svg+xml;charset=UTF-8," + quote(svg)


def seed_3d_avatars(apps, schema_editor):
    Buddy3DAvatar = apps.get_model("speaking_buddy", "Buddy3DAvatar")
    avatars = [
        {
            "name": "Nova",
            "slug": "nova-3d",
            "gender_style": "neutral",
            "age_style": "adult",
            "personality": "friendly",
            "default_voice": "Nova Warm",
            "voice_style": "warm",
            "mood": "encouraging",
            "backstory": "A calm robot mentor who keeps practice light and encouraging.",
            "thumbnail": svg_data_uri("N", "#38bdf8", "#1d4ed8"),
            "glb_file": "https://threejs.org/examples/models/gltf/RobotExpressive/RobotExpressive.glb",
            "idle_animation": "Idle",
            "talking_animation": "Talking",
            "emotion_set": {"happy": "Gentle smile", "thinking": "Tilt head", "surprised": "Brighten eyes", "encouraging": "Soft pulse"},
        },
        {
            "name": "Mila",
            "slug": "mila-3d",
            "gender_style": "female",
            "age_style": "adult",
            "personality": "teacher",
            "default_voice": "Mila Clear",
            "voice_style": "clear",
            "mood": "thinking",
            "backstory": "A precise coach who explains grammar and pronunciation clearly.",
            "thumbnail": svg_data_uri("M", "#f472b6", "#7c3aed"),
            "glb_file": "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/CesiumMan/glTF-Binary/CesiumMan.glb",
            "idle_animation": "Idle",
            "talking_animation": "Talking",
            "emotion_set": {"happy": "Head nod", "thinking": "Slow blink", "surprised": "Quick pulse", "encouraging": "Warm glow"},
        },
        {
            "name": "Rio",
            "slug": "rio-3d",
            "gender_style": "male",
            "age_style": "young",
            "personality": "casual_friend",
            "default_voice": "Rio Calm",
            "voice_style": "calm",
            "mood": "happy",
            "backstory": "A relaxed buddy who keeps the conversation flowing naturally.",
            "thumbnail": svg_data_uri("R", "#34d399", "#0f766e"),
            "glb_file": "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/Fox/glTF-Binary/Fox.glb",
            "idle_animation": "Idle",
            "talking_animation": "Talking",
            "emotion_set": {"happy": "Smile", "thinking": "Pause", "surprised": "Lean in", "encouraging": "Bounce"},
        },
        {
            "name": "Atlas",
            "slug": "atlas-3d",
            "gender_style": "male",
            "age_style": "adult",
            "personality": "interviewer",
            "default_voice": "Atlas Firm",
            "voice_style": "clear",
            "mood": "neutral",
            "backstory": "A steady voice for mock interviews and structured speaking practice.",
            "thumbnail": svg_data_uri("A", "#f59e0b", "#c2410c"),
            "glb_file": "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/Soldier/glTF-Binary/Soldier.glb",
            "idle_animation": "Idle",
            "talking_animation": "Talking",
            "emotion_set": {"happy": "Raised brow", "thinking": "Measured nod", "surprised": "Quick lean", "encouraging": "Strong pulse"},
        },
        {
            "name": "Lyra",
            "slug": "lyra-3d",
            "gender_style": "female",
            "age_style": "young",
            "personality": "friendly",
            "default_voice": "Lyra Warm",
            "voice_style": "warm",
            "mood": "encouraging",
            "backstory": "A bright buddy who gently nudges the learner forward.",
            "thumbnail": svg_data_uri("L", "#a78bfa", "#7c3aed"),
            "glb_file": "https://threejs.org/examples/models/gltf/RobotExpressive/RobotExpressive.glb",
            "idle_animation": "Idle",
            "talking_animation": "Talking",
            "emotion_set": {"happy": "Smile", "thinking": "Look aside", "surprised": "Light flash", "encouraging": "Pulse"},
        },
        {
            "name": "Orion",
            "slug": "orion-3d",
            "gender_style": "male",
            "age_style": "senior",
            "personality": "strict_coach",
            "default_voice": "Orion Deep",
            "voice_style": "calm",
            "mood": "thinking",
            "backstory": "An experienced coach that keeps the learner focused on accuracy.",
            "thumbnail": svg_data_uri("O", "#60a5fa", "#1e3a8a"),
            "glb_file": "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/CesiumMan/glTF-Binary/CesiumMan.glb",
            "idle_animation": "Idle",
            "talking_animation": "Talking",
            "emotion_set": {"happy": "Approving nod", "thinking": "Slow blink", "surprised": "Sharp pulse", "encouraging": "Blue glow"},
        },
        {
            "name": "Astra",
            "slug": "astra-3d",
            "gender_style": "female",
            "age_style": "adult",
            "personality": "teacher",
            "default_voice": "Astra Clear",
            "voice_style": "clear",
            "mood": "encouraging",
            "backstory": "A patient teacher with clear feedback and short replies.",
            "thumbnail": svg_data_uri("A", "#fb7185", "#be185d"),
            "glb_file": "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/Fox/glTF-Binary/Fox.glb",
            "idle_animation": "Idle",
            "talking_animation": "Talking",
            "emotion_set": {"happy": "Soft smile", "thinking": "Pause", "surprised": "Bright blink", "encouraging": "Warm pulse"},
        },
        {
            "name": "Vega",
            "slug": "vega-3d",
            "gender_style": "neutral",
            "age_style": "young",
            "personality": "casual_friend",
            "default_voice": "Vega Calm",
            "voice_style": "calm",
            "mood": "happy",
            "backstory": "A friendly buddy that keeps conversation relaxed and natural.",
            "thumbnail": svg_data_uri("V", "#22c55e", "#166534"),
            "glb_file": "https://threejs.org/examples/models/gltf/RobotExpressive/RobotExpressive.glb",
            "idle_animation": "Idle",
            "talking_animation": "Talking",
            "emotion_set": {"happy": "Nod", "thinking": "Tilt", "surprised": "Quick flash", "encouraging": "Soft glow"},
        },
        {
            "name": "Echo",
            "slug": "echo-3d",
            "gender_style": "neutral",
            "age_style": "adult",
            "personality": "interviewer",
            "default_voice": "Echo Neutral",
            "voice_style": "clear",
            "mood": "neutral",
            "backstory": "A balanced interview partner who asks concise follow-up questions.",
            "thumbnail": svg_data_uri("E", "#eab308", "#854d0e"),
            "glb_file": "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/Soldier/glTF-Binary/Soldier.glb",
            "idle_animation": "Idle",
            "talking_animation": "Talking",
            "emotion_set": {"happy": "Nod", "thinking": "Pause", "surprised": "Blink", "encouraging": "Pulse"},
        },
        {
            "name": "Sol",
            "slug": "sol-3d",
            "gender_style": "female",
            "age_style": "senior",
            "personality": "friendly",
            "default_voice": "Sol Warm",
            "voice_style": "warm",
            "mood": "encouraging",
            "backstory": "A warm mentor with a calm presence and supportive prompts.",
            "thumbnail": svg_data_uri("S", "#f97316", "#9a3412"),
            "glb_file": "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/CesiumMan/glTF-Binary/CesiumMan.glb",
            "idle_animation": "Idle",
            "talking_animation": "Talking",
            "emotion_set": {"happy": "Smile", "thinking": "Glance aside", "surprised": "Bright blink", "encouraging": "Glow"},
        },
    ]
    for avatar in avatars:
        Buddy3DAvatar.objects.update_or_create(slug=avatar["slug"], defaults=avatar)


def unseed_3d_avatars(apps, schema_editor):
    Buddy3DAvatar = apps.get_model("speaking_buddy", "Buddy3DAvatar")
    Buddy3DAvatar.objects.filter(slug__in=[
        "nova-3d",
        "mila-3d",
        "rio-3d",
        "atlas-3d",
        "lyra-3d",
        "orion-3d",
        "astra-3d",
        "vega-3d",
        "echo-3d",
        "sol-3d",
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("speaking_buddy", "0002_alter_buddymistake_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buddy3DAvatar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("gender_style", models.CharField(blank=True, max_length=40)),
                ("age_style", models.CharField(blank=True, max_length=40)),
                ("personality", models.CharField(blank=True, max_length=40)),
                ("default_voice", models.CharField(blank=True, max_length=120)),
                ("voice_style", models.CharField(blank=True, max_length=40)),
                ("mood", models.CharField(blank=True, max_length=40)),
                ("backstory", models.TextField(blank=True)),
                ("thumbnail", models.CharField(blank=True, max_length=1000)),
                ("glb_file", models.CharField(blank=True, max_length=1000)),
                ("idle_animation", models.CharField(blank=True, max_length=120)),
                ("talking_animation", models.CharField(blank=True, max_length=120)),
                ("emotion_set", models.JSONField(blank=True, default=dict)),
                ("is_premium", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BuddyGeneratedAvatar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_image", models.ImageField(blank=True, null=True, upload_to="speaking_buddy/generated_sources/")),
                ("generated_glb_url", models.CharField(blank=True, max_length=1000)),
                ("generated_thumbnail_url", models.CharField(blank=True, max_length=1000)),
                ("provider", models.CharField(blank=True, max_length=80)),
                ("provider_job_id", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed")], default="pending", max_length=20)),
                ("consent_confirmed", models.BooleanField(default=False)),
                ("user_generated", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="generated_buddy_avatars", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="buddysettings",
            name="avatar_render_mode",
            field=models.CharField(choices=[("2d", "2D"), ("3d", "3D"), ("generated_3d", "Generated 3D")], default="2d", max_length=20),
        ),
        migrations.AddField(
            model_name="buddysettings",
            name="selected_3d_avatar_slug",
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="buddysettings",
            name="selected_generated_avatar",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="speaking_buddy.buddygeneratedavatar"),
        ),
        migrations.RunPython(seed_3d_avatars, unseed_3d_avatars),
    ]
