# Generated by Django 5.1.15 on 2026-06-12 20:43

import apps.speaking_buddy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking_buddy", "0003_buddy3davatar_buddygeneratedavatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddy3davatar",
            name="emotion_set",
            field=models.JSONField(blank=True, default=apps.speaking_buddy.models.default_dict),
        ),
    ]
