# Generated by Django 5.1.15 on 2026-06-13 21:29

import apps.speaking_buddy.models
import django.db.models.deletion
from django.db import migrations, models


def seed_free_avatar_catalog(apps, schema_editor):
    Buddy3DAvatar = apps.get_model("speaking_buddy", "Buddy3DAvatar")
    old_slugs = [
        "nova-3d", "mila-3d", "rio-3d", "atlas-3d", "lyra-3d",
        "orion-3d", "astra-3d", "vega-3d", "echo-3d", "sol-3d",
    ]
    Buddy3DAvatar.objects.filter(slug__in=old_slugs).delete()
    names = ["Emma", "Leo", "Zara", "Noah", "Luna", "Kai", "Mila", "Omar", "Aria", "Atlas"]
    female_names = {"Emma", "Zara", "Luna", "Mila", "Aria"}
    for index, name in enumerate(names):
        slug = name.lower()
        Buddy3DAvatar.objects.update_or_create(
            slug=slug,
            defaults={
                "name": name,
                "gender_style": "female" if name in female_names else "male",
                "age_style": "adult",
                "personality": "friendly" if index % 2 == 0 else "teacher",
                "default_voice": f"{name} voice",
                "voice_style": "warm" if index % 2 == 0 else "clear",
                "mood": "encouraging",
                "backstory": "A free local AI speaking buddy avatar.",
                "thumbnail": "",
                "thumbnail_url": "",
                "glb_file": f"/assets/buddy3d/{slug}.vrm",
                "model_url": f"/assets/buddy3d/{slug}.vrm",
                "supported_blendshapes": {
                    "mouthOpen": ["aa", "mouthOpen", "jawOpen"],
                    "blink": ["blink", "blinkLeft", "blinkRight"],
                    "happy": ["happy", "smile"],
                },
                "idle_animation": "idle",
                "talking_animation": "talking",
                "listening_animation": "listening",
                "thinking_animation": "thinking",
                "emotion_set": {"happy": "happy", "encouraging": "happy"},
                "is_premium": False,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_buddy', '0004_alter_buddy3davatar_emotion_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddy3davatar',
            name='listening_animation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buddy3davatar',
            name='model_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='buddy3davatar',
            name='supported_blendshapes',
            field=models.JSONField(blank=True, default=apps.speaking_buddy.models.default_dict),
        ),
        migrations.AddField(
            model_name='buddy3davatar',
            name='thinking_animation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buddy3davatar',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='buddygeneratedavatar',
            name='appearance_config',
            field=models.JSONField(blank=True, default=apps.speaking_buddy.models.default_dict),
        ),
        migrations.AddField(
            model_name='buddygeneratedavatar',
            name='generated_model_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='buddygeneratedavatar',
            name='generated_thumbnail',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='buddygeneratedavatar',
            name='generation_logs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='buddymessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buddymistake',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buddysession',
            name='emotion_timeline',
            field=models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list),
        ),
        migrations.AddField(
            model_name='buddysession',
            name='selected_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='speaking_buddy.buddy3davatar'),
        ),
        migrations.AddField(
            model_name='buddysettings',
            name='selected_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_settings', to='speaking_buddy.buddy3davatar'),
        ),
        migrations.RunPython(seed_free_avatar_catalog, migrations.RunPython.noop),
    ]
