# Generated by Django 5.1.15 on 2026-06-15 07:21

from django.db import migrations, models


def preserve_existing_voice_preferences(apps, schema_editor):
    BuddySettings = apps.get_model("speaking_buddy", "BuddySettings")
    BuddySession = apps.get_model("speaking_buddy", "BuddySession")
    for buddy_settings in BuddySettings.objects.all():
        selected_voice = "cedar" if buddy_settings.voice_gender == "male" else "marin"
        BuddySettings.objects.filter(pk=buddy_settings.pk).update(selected_voice=selected_voice)
        BuddySession.objects.filter(profile_id=buddy_settings.profile_id).update(selected_voice=selected_voice)


class Migration(migrations.Migration):
    dependencies = [
        ("speaking_buddy", "0007_buddy3davatar_base_hair_material_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buddysession",
            name="selected_voice",
            field=models.CharField(
                choices=[("marin", "Female Adult"), ("cedar", "Male Adult")],
                default="marin",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="buddysettings",
            name="selected_voice",
            field=models.CharField(
                choices=[("marin", "Female Adult"), ("cedar", "Male Adult")],
                default="marin",
                max_length=20,
            ),
        ),
        migrations.RunPython(preserve_existing_voice_preferences, migrations.RunPython.noop),
    ]
