# Generated by Django 5.1.15 on 2026-06-15 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking_buddy", "0008_buddysession_selected_voice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="buddysession",
            name="usage_counted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BuddyUsageQuota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("free_conversation_limit", models.PositiveSmallIntegerField(default=100)),
                ("conversations_used", models.PositiveIntegerField(default=0)),
                ("last_reset_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_buddy_usage_quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
