# Generated by Django 5.1.15 on 2026-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking_buddy", "0009_buddysession_usage_counted_buddyusagequota"),
    ]

    operations = [
        migrations.AddField(
            model_name="buddysession",
            name="client_closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buddysession",
            name="end_reason",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
