# Generated by Django 5.1.15 on 2026-07-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking_buddy", "0010_buddysession_client_closed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddysession",
            name="selected_voice",
            field=models.CharField(
                choices=[
                    ("marin", "Female Adult (legacy)"),
                    ("cedar", "Male Adult (legacy)"),
                    ("alloy", "Alloy (Neutral/Female Adult)"),
                    ("shimmer", "Shimmer (Female Young)"),
                    ("nova", "Nova (Female Senior)"),
                    ("echo", "Echo (Male Adult/Young)"),
                    ("onyx", "Onyx (Male Senior)"),
                ],
                default="marin",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="buddysettings",
            name="selected_voice",
            field=models.CharField(
                choices=[
                    ("marin", "Female Adult (legacy)"),
                    ("cedar", "Male Adult (legacy)"),
                    ("alloy", "Alloy (Neutral/Female Adult)"),
                    ("shimmer", "Shimmer (Female Young)"),
                    ("nova", "Nova (Female Senior)"),
                    ("echo", "Echo (Male Adult/Young)"),
                    ("onyx", "Onyx (Male Senior)"),
                ],
                default="marin",
                max_length=20,
            ),
        ),
    ]
