# Generated by Django 5.1.15 on 2026-07-08 18:51

import apps.speaking_buddy.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking_buddy", "0011_alter_buddysession_selected_voice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuddyScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("nl", "Dutch"),
                            ("hi", "Hindi"),
                            ("ur", "Urdu"),
                            ("ar", "Arabic"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("other", "Other"),
                        ],
                        default="en",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("government", "Government / Gemeente"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                            ("work", "Work"),
                            ("customer_service", "Customer Service"),
                            ("food", "Food & Dining"),
                            ("shopping", "Shopping"),
                            ("travel", "Travel"),
                            ("driving", "Driving"),
                            ("daily_life", "Daily Life"),
                            ("business", "Business"),
                            ("presentation", "Presentation"),
                        ],
                        default="daily_life",
                        max_length=40,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("elementary", "Elementary"),
                            ("intermediate", "Intermediate"),
                            ("upper_intermediate", "Upper Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=30,
                    ),
                ),
                ("system_prompt", models.TextField(blank=True)),
                ("opening_message", models.TextField(blank=True)),
                ("expected_skills", models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ("vocabulary_focus", models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ("is_kids_safe", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["language", "category", "title"],
            },
        ),
        migrations.AddField(
            model_name="buddysettings",
            name="kids_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="buddyvocabulary",
            name="last_result",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="buddyvocabulary",
            name="next_review_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buddyvocabulary",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="buddyvocabulary",
            name="review_status",
            field=models.CharField(
                choices=[("new", "New"), ("learning", "Learning"), ("mastered", "Mastered")],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="buddysession",
            name="selected_scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="speaking_buddy.buddyscenario",
            ),
        ),
        migrations.CreateModel(
            name="BuddySessionReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "fluency_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "grammar_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "vocabulary_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "confidence_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "completeness_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("strengths", models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ("improvement_points", models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ("corrected_sentences", models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ("vocabulary_learned", models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ("next_practice_recommendation", models.TextField(blank=True)),
                ("report_summary", models.TextField(blank=True)),
                ("is_fallback", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="speaking_buddy.buddysession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_session_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuddyNextLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("nl", "Dutch"),
                            ("hi", "Hindi"),
                            ("ur", "Urdu"),
                            ("ar", "Arabic"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("other", "Other"),
                        ],
                        default="en",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("elementary", "Elementary"),
                            ("intermediate", "Intermediate"),
                            ("upper_intermediate", "Upper Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=30,
                    ),
                ),
                ("focus_areas", models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                (
                    "recommended_scenarios",
                    models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list),
                ),
                ("vocabulary_to_review", models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ("mistakes_to_fix", models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_lessons",
                        to="speaking_buddy.buddyprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_next_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_lessons",
                        to="speaking_buddy.buddysessionreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuddyWeakArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("grammar", "Grammar"),
                            ("vocabulary", "Vocabulary"),
                            ("fluency", "Fluency"),
                            ("pronunciation", "Pronunciation"),
                            ("listening", "Listening"),
                            ("confidence", "Confidence"),
                        ],
                        default="grammar",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("nl", "Dutch"),
                            ("hi", "Hindi"),
                            ("ur", "Urdu"),
                            ("ar", "Arabic"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("other", "Other"),
                        ],
                        default="en",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("evidence", models.JSONField(blank=True, default=apps.speaking_buddy.models.default_list)),
                ("improvement_plan", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("improving", "Improving"), ("resolved", "Resolved")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weak_area_records",
                        to="speaking_buddy.buddyprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_weak_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-updated_at"],
                "unique_together": {("profile", "area_type", "title", "language")},
            },
        ),
    ]
