# Generated by Django 5.1.15 on 2026-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_buddy', '0012_buddyscenario_buddysettings_kids_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddygeneratedavatar',
            name='source_image_public_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='buddygeneratedavatar',
            name='source_image_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
