# Generated by Django 5.1.15 on 2026-07-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speaking_buddy", "0013_buddygeneratedavatar_source_image_public_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buddysession",
            name="resolved_voice",
            field=models.CharField(
                blank=True,
                help_text="The actual Realtime-API-supported voice sent to OpenAI for this session, after resolve_realtime_voice() sanitization. May differ from selected_voice if selected_voice was a legacy/unsupported value (e.g. 'nova').",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="buddysession",
            name="selected_voice",
            field=models.CharField(
                choices=[
                    ("marin", "Marin (Female Adult)"),
                    ("cedar", "Cedar (Male Adult)"),
                    ("alloy", "Alloy (Neutral)"),
                    ("shimmer", "Shimmer (Female Young)"),
                    ("coral", "Coral (Female Warm)"),
                    ("sage", "Sage (Female Calm)"),
                    ("echo", "Echo (Male Adult/Young)"),
                    ("ash", "Ash (Male Warm)"),
                    ("ballad", "Ballad"),
                    ("verse", "Verse"),
                ],
                default="marin",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="buddysettings",
            name="selected_voice",
            field=models.CharField(
                choices=[
                    ("marin", "Marin (Female Adult)"),
                    ("cedar", "Cedar (Male Adult)"),
                    ("alloy", "Alloy (Neutral)"),
                    ("shimmer", "Shimmer (Female Young)"),
                    ("coral", "Coral (Female Warm)"),
                    ("sage", "Sage (Female Calm)"),
                    ("echo", "Echo (Male Adult/Young)"),
                    ("ash", "Ash (Male Warm)"),
                    ("ballad", "Ballad"),
                    ("verse", "Verse"),
                ],
                default="marin",
                max_length=20,
            ),
        ),
    ]
