# Generated by Django 5.1.15 on 2026-06-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_theory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivinglesson',
            name='common_mistakes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='drivinglesson',
            name='exam_tips',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='drivinglesson',
            name='key_takeaways',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='drivinglesson',
            name='learning_objectives',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='drivinglessonsection',
            name='callout_boxes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='drivinglessonsection',
            name='illustration_hint',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drivingquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('scenario', 'Scenario Based'), ('sign', 'Sign Recognition'), ('hazard', 'Hazard Recognition')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='drivingquestion',
            name='sign_hint',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drivingtopic',
            name='color_theme',
            field=models.CharField(default='rgba(99,102,241,0.15)', max_length=80),
        ),
        migrations.AddField(
            model_name='drivingtopic',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='drivingtopic',
            name='exam_weight',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='drivingtopic',
            name='learning_objectives',
            field=models.JSONField(default=list),
        ),
    ]
