# Generated by Django 5.1.15 on 2026-06-08 17:24

from django.db import migrations


def seed_v2(apps, schema_editor):
    # Guard: defer to 0008_reseed_all_topics if v3 columns aren't present yet.
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        table_cols = {col.name for col in conn.introspection.get_table_description(cursor, "driving_theory_drivingtopic")}
    if "recommended_next" not in table_cols:
        return

    from django.core.management import call_command
    call_command("seed_driving_theory", verbosity=0)


def unseed_v2(apps, schema_editor):
    # Reverse: remove the 3 new topics added in V2 (existing 12 were already there)
    DrivingTopic = apps.get_model("driving_theory", "DrivingTopic")
    DrivingTopic.objects.filter(
        slug__in=[
            "introduction-to-dutch-driving",
            "road-users",
            "basic-traffic-rules",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("driving_theory", "0002_seed_driving_theory"),
        ("driving_theory", "0003_add_enhanced_fields"),
    ]

    operations = [
        migrations.RunPython(seed_v2, reverse_code=unseed_v2),
    ]
