# Generated by Django 5.1.15 on 2026-06-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driving_theory", "0003_add_enhanced_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivingtopic",
            name="recommended_next",
            field=models.JSONField(default=list),
        ),
    ]
