# Generated by Django 5.1.15 on 2026-06-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driving_theory", "0005_v3_add_tags_image_url_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivingquestion",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="drivingquestion",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="mocktestattempt",
            name="topic_breakdown",
            field=models.JSONField(default=dict),
        ),
    ]
