# Generated by Django 5.1.15 on 2026-06-09 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_theory', '0012_reseed_after_nl_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousMockTestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.FloatField(blank=True, null=True)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
