# Generated by Django 5.1.15 on 2026-06-11 09:34

import apps.templates_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0003_resumetemplate_supports_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumetemplate',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='category',
            field=models.CharField(choices=[('ATS Friendly', 'ATS Friendly'), ('Modern', 'Modern'), ('Executive', 'Executive'), ('Creative', 'Creative'), ('Student / Fresher', 'Student / Fresher'), ('Developer / Tech', 'Developer / Tech'), ('European CV', 'European CV'), ('Minimal', 'Minimal'), ('Photo CV', 'Photo CV')], default='ATS Friendly', max_length=40),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='default_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='is_ats_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='layout_type',
            field=models.CharField(default='single-column', max_length=60),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='preview_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='supported_formats',
            field=models.JSONField(default=apps.templates_app.models.default_supported_formats),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
