from django.urls import path

from .views import (
    buddy_3d_avatar_view,
    buddy_avatar_view,
    buddy_generated_avatar_detail_view,
    buddy_generated_avatar_regenerate_view,
    buddy_generated_avatar_view,
    buddy_history_view,
    buddy_memory_detail_view,
    buddy_memory_view,
    buddy_mistakes_view,
    buddy_profile_view,
    buddy_realtime_token_view,
    buddy_session_end_view,
    buddy_session_message_view,
    buddy_session_start_view,
    buddy_session_view,
    buddy_settings_view,
    buddy_usage_view,
    buddy_vocabulary_view,
)

urlpatterns = [
    path("profile/", buddy_profile_view),
    path("settings/", buddy_settings_view),
    path("avatar/", buddy_avatar_view),
    path("avatars/", buddy_3d_avatar_view),
    path("avatar-3d/", buddy_3d_avatar_view),
    path("avatar-generated/", buddy_generated_avatar_view),
    path("generated-avatar/", buddy_generated_avatar_view),
    path("avatar-generated/<int:pk>/", buddy_generated_avatar_detail_view),
    path("generated-avatar/<int:pk>/", buddy_generated_avatar_detail_view),
    path("generated-avatar/<int:pk>/regenerate/", buddy_generated_avatar_regenerate_view),
    path("memory/", buddy_memory_view),
    path("memory/<int:pk>/", buddy_memory_detail_view),
    path("history/", buddy_history_view),
    path("vocabulary/", buddy_vocabulary_view),
    path("mistakes/", buddy_mistakes_view),
    path("session/", buddy_session_view),
    path("session/start/", buddy_session_start_view),
    path("session/end/", buddy_session_end_view),
    path("session/message/", buddy_session_message_view),
    path("usage/", buddy_usage_view),
    path("realtime-token/", buddy_realtime_token_view),
]
