# Generated by Django 5.1.15 on 2026-06-29 10:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureWiseOrganization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_sw_orgs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecureWiseIntegration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("jira", "Jira"),
                            ("slack", "Slack"),
                            ("github_issues", "GitHub Issues"),
                            ("pagerduty", "PagerDuty"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("config", models.JSONField(blank=True, default=dict, help_text="Non-sensitive config values.")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sw_created_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="securewise.securewiseorganization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecureWiseGitIntegration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("bitbucket", "Bitbucket"),
                            ("azure_devops", "Azure DevOps"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("personal_access_token", "Personal Access Token"),
                            ("oauth", "OAuth"),
                            ("github_app", "GitHub App"),
                        ],
                        default="personal_access_token",
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("base_url", models.URLField(default="https://github.com")),
                (
                    "_encrypted_access_token",
                    models.BinaryField(blank=True, db_column="encrypted_access_token", null=True),
                ),
                ("token_last_four", models.CharField(blank=True, max_length=4)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sw_git_integrations_connected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_integrations",
                        to="securewise.securewiseorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Git Integration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecureWiseAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("organization_created", "Organization Created"),
                            ("project_created", "Project Created"),
                            ("scan_started", "Scan Started"),
                            ("scan_completed", "Scan Completed"),
                            ("scan_failed", "Scan Failed"),
                            ("finding_status_changed", "Finding Status Changed"),
                            ("report_generated", "Report Generated"),
                            ("git_integration_created", "Git Integration Created"),
                            ("git_integration_updated", "Git Integration Updated"),
                            ("git_integration_deleted", "Git Integration Deleted"),
                            ("token_used_for_scan", "Token Used for Scan"),
                            ("token_failed", "Token Failed"),
                            ("repository_added", "Repository Added"),
                        ],
                        max_length=60,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=60)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sw_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="securewise.securewiseorganization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecureWiseProject",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="medium",
                        help_text="Overall risk classification for this project.",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sw_created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="securewise.securewiseorganization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("organization", "slug")},
            },
        ),
        migrations.CreateModel(
            name="SecureWiseRepository",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("bitbucket", "Bitbucket"),
                            ("azure_devops", "Azure DevOps"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "repository_url",
                    models.CharField(max_length=500, validators=[django.core.validators.URLValidator()]),
                ),
                ("clone_url", models.CharField(blank=True, max_length=500)),
                ("default_branch", models.CharField(default="main", max_length=100)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private"), ("internal", "Internal")],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "access_mode",
                    models.CharField(
                        choices=[("public", "Public"), ("integration", "Integration")], default="public", max_length=20
                    ),
                ),
                ("last_access_check_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_access_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accessible", "Accessible"),
                            ("forbidden", "Forbidden"),
                            ("not_found", "Not Found"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sw_created_repositories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        help_text="Git integration used for private repo access.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repositories",
                        to="securewise.securewisegitintegration",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="securewise.securewiseorganization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repositories",
                        to="securewise.securewiseproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecureWiseScan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("sast", "SAST"),
                            ("dast", "DAST"),
                            ("sca", "SCA"),
                            ("secrets", "Secret Scanning"),
                            ("iac", "IaC"),
                            ("container", "Container"),
                            ("api", "API Security"),
                            ("full", "Full Scan"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("branch", models.CharField(blank=True, max_length=200)),
                ("commit_sha", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("scanner_metadata", models.JSONField(blank=True, default=dict)),
                ("quality_gate_passed", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="securewise.securewiseorganization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="securewise.securewiseproject",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scans",
                        to="securewise.securewiserepository",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sw_triggered_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecureWiseReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "format",
                    models.CharField(
                        choices=[("json", "JSON"), ("html", "HTML"), ("pdf", "PDF")], default="json", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("generating", "Generating"), ("ready", "Ready"), ("failed", "Failed")],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("report_data", models.JSONField(blank=True, default=dict)),
                ("quality_gate_passed", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sw_generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="securewise.securewiseorganization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="securewise.securewiseproject",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="securewise.securewisescan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecureWiseFinding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=500)),
                ("cwe_id", models.CharField(blank=True, help_text="e.g. CWE-79", max_length=20)),
                ("owasp_category", models.CharField(blank=True, help_text="e.g. A01:2021", max_length=50)),
                (
                    "scanner_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sast", "SAST"),
                            ("dast", "DAST"),
                            ("sca", "SCA"),
                            ("secrets", "Secret Scanning"),
                            ("iac", "IaC"),
                            ("container", "Container"),
                            ("api", "API Security"),
                            ("full", "Full Scan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[("very_high", "Very High"), ("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("fixed", "Fixed"),
                            ("accepted_risk", "Accepted Risk"),
                            ("false_positive", "False Positive"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("risk", models.TextField(blank=True)),
                ("impact", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("bad_code_example", models.TextField(blank=True)),
                ("fixed_code_example", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("fingerprint", models.CharField(blank=True, db_index=True, max_length=128)),
                (
                    "ai_fix_suggestion",
                    models.TextField(blank=True, help_text="AI-generated fix recommendation. TODO: integrate LLM."),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sw_reviewed_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="securewise.securewiseorganization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="securewise.securewiseproject",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="securewise.securewisescan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecureWiseScanPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("scan_types", models.JSONField(default=list, help_text="List of scan type keys, e.g. ['sast','sca']")),
                (
                    "fail_on_severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                ("max_critical", models.IntegerField(default=0)),
                ("max_high", models.IntegerField(default=5)),
                (
                    "schedule_cron",
                    models.CharField(blank=True, help_text="Cron expression for auto-scheduling.", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sw_created_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_policies",
                        to="securewise.securewiseorganization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_policies",
                        to="securewise.securewiseproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Policy",
                "verbose_name_plural": "Scan Policies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="securewisescan",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scans",
                to="securewise.securewisescanpolicy",
            ),
        ),
        migrations.CreateModel(
            name="SecureWiseMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("security_engineer", "Security Engineer"),
                            ("developer", "Developer"),
                            ("auditor", "Auditor"),
                        ],
                        default="developer",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sw_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sw_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="securewise.securewiseorganization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "unique_together": {("organization", "user")},
            },
        ),
    ]
