# Generated by Django 5.1.15 on 2026-07-02 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securewise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securewisescan",
            name="api_spec_url",
            field=models.CharField(
                blank=True, help_text="Path or URL to an OpenAPI/Swagger spec for API scanning.", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="securewisescan",
            name="docker_image",
            field=models.CharField(
                blank=True, help_text="Docker image reference for container scanning.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="securewisescan",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0, help_text="Scan progress percentage (0-100)."),
        ),
        migrations.AddField(
            model_name="securewisescan",
            name="selected_engines",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Resolved list of engines this scan will run/ran, e.g. ['sast','sca'].",
            ),
        ),
        migrations.AddField(
            model_name="securewisescan",
            name="target_url",
            field=models.URLField(blank=True, help_text="Target URL for DAST scanning."),
        ),
        migrations.AlterField(
            model_name="securewiseauditlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("organization_created", "Organization Created"),
                    ("project_created", "Project Created"),
                    ("scan_started", "Scan Started"),
                    ("scan_completed", "Scan Completed"),
                    ("scan_failed", "Scan Failed"),
                    ("finding_status_changed", "Finding Status Changed"),
                    ("report_generated", "Report Generated"),
                    ("git_integration_created", "Git Integration Created"),
                    ("git_integration_updated", "Git Integration Updated"),
                    ("git_integration_deleted", "Git Integration Deleted"),
                    ("token_used_for_scan", "Token Used for Scan"),
                    ("token_failed", "Token Failed"),
                    ("repository_added", "Repository Added"),
                    ("scan_engine_started", "Scan Engine Started"),
                    ("scan_engine_completed", "Scan Engine Completed"),
                    ("finding_created", "Finding Created"),
                ],
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="securewisescan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("cloning", "Cloning Repository"),
                    ("running_sast", "Running SAST"),
                    ("running_sca", "Running SCA"),
                    ("running_secrets", "Running Secret Scan"),
                    ("running_iac", "Running IaC Scan"),
                    ("running_container", "Running Container Scan"),
                    ("running_api", "Running API Scan"),
                    ("running_dast", "Running DAST"),
                    ("normalizing", "Normalizing Results"),
                    ("completed", "Completed"),
                    ("completed_with_warnings", "Completed with Warnings"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SecureWiseScanEngineResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("sast", "SAST"),
                            ("sca", "SCA"),
                            ("secrets", "Secret Scanning"),
                            ("dast", "DAST"),
                            ("iac", "IaC"),
                            ("container", "Container"),
                            ("api", "API Security"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("findings_count", models.IntegerField(default=0)),
                ("skipped_reason", models.TextField(blank=True)),
                (
                    "raw_summary",
                    models.JSONField(blank=True, default=dict, help_text="Tool used, files scanned, deps parsed, etc."),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engine_results",
                        to="securewise.securewisescan",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
