# Generated by Django 5.1.15 on 2026-07-02 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securewise", "0002_securewisescan_api_spec_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securewisefinding",
            name="first_seen_scan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings_first_seen",
                to="securewise.securewisescan",
            ),
        ),
        migrations.AddField(
            model_name="securewisefinding",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, help_text="When this issue was last re-detected.", null=True),
        ),
        migrations.AddField(
            model_name="securewisefinding",
            name="occurrence_count",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of scans (across time) that have re-detected this issue."
            ),
        ),
        migrations.AddField(
            model_name="securewisescan",
            name="bypass_quality_gate",
            field=models.BooleanField(
                default=False, help_text="User explicitly opted out of quality gate enforcement for this scan."
            ),
        ),
        migrations.AddField(
            model_name="securewisescan",
            name="bypass_reason",
            field=models.TextField(blank=True, help_text="Why the quality gate was bypassed for this scan."),
        ),
        migrations.AddField(
            model_name="securewisescan",
            name="retry_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retries",
                to="securewise.securewisescan",
            ),
        ),
        migrations.AddField(
            model_name="securewisescanpolicy",
            name="allow_accepted_risks",
            field=models.BooleanField(
                default=True, help_text="Findings marked 'Accepted Risk' don't count against the gate."
            ),
        ),
        migrations.AddField(
            model_name="securewisescanpolicy",
            name="allow_false_positives",
            field=models.BooleanField(
                default=True, help_text="Findings marked 'False Positive' don't count against the gate."
            ),
        ),
        migrations.AddField(
            model_name="securewisescanpolicy",
            name="fail_on_new_findings_only",
            field=models.BooleanField(
                default=False,
                help_text="Only evaluate findings first discovered by this scan, ignoring pre-existing recurring issues.",
            ),
        ),
        migrations.AddField(
            model_name="securewisescanpolicy",
            name="fail_on_secrets",
            field=models.BooleanField(default=True, help_text="Fail the gate if any open secret finding exists."),
        ),
        migrations.AddField(
            model_name="securewisescanpolicy",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Automatically applied to new scans in this organization when no policy is explicitly chosen.",
            ),
        ),
        migrations.AddField(
            model_name="securewisescanpolicy",
            name="max_medium",
            field=models.IntegerField(default=-1, help_text="-1 = unlimited."),
        ),
    ]
