# Generated by Django 5.1.15 on 2026-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securewise", "0003_securewisefinding_first_seen_scan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securewisefinding",
            name="code_snippet",
            field=models.TextField(blank=True),
        ),
    ]
