# Generated by Django 5.1.15 on 2026-07-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securewise", "0004_securewisefinding_code_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="securewisefinding",
            name="pr_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securewisefinding",
            name="pr_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="securewisefinding",
            name="ticket_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securewisefinding",
            name="ticket_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="securewiseauditlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("organization_created", "Organization Created"),
                    ("project_created", "Project Created"),
                    ("scan_started", "Scan Started"),
                    ("scan_completed", "Scan Completed"),
                    ("scan_failed", "Scan Failed"),
                    ("finding_status_changed", "Finding Status Changed"),
                    ("report_generated", "Report Generated"),
                    ("git_integration_created", "Git Integration Created"),
                    ("git_integration_updated", "Git Integration Updated"),
                    ("git_integration_deleted", "Git Integration Deleted"),
                    ("token_used_for_scan", "Token Used for Scan"),
                    ("token_failed", "Token Failed"),
                    ("repository_added", "Repository Added"),
                    ("scan_engine_started", "Scan Engine Started"),
                    ("scan_engine_completed", "Scan Engine Completed"),
                    ("finding_created", "Finding Created"),
                    ("finding_ticket_created", "Finding Ticket Created"),
                    ("finding_ticket_failed", "Finding Ticket Failed"),
                    ("finding_pr_created", "Finding PR Created"),
                    ("finding_pr_failed", "Finding PR Failed"),
                ],
                max_length=60,
            ),
        ),
    ]
