# Generated by Django 5.1.15 on 2026-07-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securewise", "0006_alter_securewiseauditlog_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securewisefinding",
            name="ai_fix_suggestion",
            field=models.TextField(
                blank=True, help_text="AI-generated fix recommendation (see services/ai_recommendation.py)."
            ),
        ),
        migrations.AlterField(
            model_name="securewisescan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("cloning", "Cloning Repository"),
                    ("running_sast", "Running SAST"),
                    ("running_sca", "Running SCA"),
                    ("running_secrets", "Running Secret Scan"),
                    ("running_iac", "Running IaC Scan"),
                    ("running_container", "Running Container Scan"),
                    ("running_api", "Running API Scan"),
                    ("running_dast", "Running DAST"),
                    ("normalizing", "Normalizing Results"),
                    ("completed", "Completed"),
                    ("completed_with_warnings", "Completed with Warnings"),
                    ("completed_partial", "Completed (Partial Coverage — fallback/passive engines only)"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
