# Generated by Django 5.1.15 on 2026-10-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securewise", "0014_pentesttestproposal_estimated_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="securewiseworkerregistration",
            name="metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
