# Generated by Django 5.1.15 on 2026-10-10 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securewise", "0015_securewiseworkerregistration_metrics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureWiseGitHubAppState",
            fields=[
                ("state_digest", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecureWiseGitHubWebhookDelivery",
            fields=[
                ("delivery_id", models.CharField(max_length=200, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=100)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="securewiserepository",
            name="provider_repository_id",
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="securewiseauditlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("organization_created", "Organization Created"),
                    ("project_created", "Project Created"),
                    ("scan_started", "Scan Started"),
                    ("scan_completed", "Scan Completed"),
                    ("scan_failed", "Scan Failed"),
                    ("finding_status_changed", "Finding Status Changed"),
                    ("report_generated", "Report Generated"),
                    ("git_integration_created", "Git Integration Created"),
                    ("git_integration_updated", "Git Integration Updated"),
                    ("git_integration_deleted", "Git Integration Deleted"),
                    ("github_app_installation_created", "GitHub App Installation Created"),
                    ("github_app_repository_synced", "GitHub App Repository Synced"),
                    ("github_app_webhook_received", "GitHub App Webhook Received"),
                    ("token_used_for_scan", "Token Used for Scan"),
                    ("token_failed", "Token Failed"),
                    ("repository_added", "Repository Added"),
                    ("scan_engine_started", "Scan Engine Started"),
                    ("scan_engine_completed", "Scan Engine Completed"),
                    ("finding_created", "Finding Created"),
                    ("finding_ticket_created", "Finding Ticket Created"),
                    ("finding_ticket_failed", "Finding Ticket Failed"),
                    ("finding_pr_created", "Finding PR Created"),
                    ("finding_pr_failed", "Finding PR Failed"),
                    ("scan_policy_updated", "Scan Policy Updated"),
                    ("scan_policy_deleted", "Scan Policy Deleted"),
                    ("pentest_session_created", "Pentest Session Created"),
                    ("pentest_session_completed", "Pentest Session Completed"),
                    ("pentest_plan_generated", "Pentest Plan Generated"),
                    ("pentest_proposal_approved", "Pentest Proposal Approved"),
                    ("pentest_proposal_rejected", "Pentest Proposal Rejected"),
                    ("pentest_execution_queued", "Pentest Execution Queued"),
                    ("pentest_ai_planner_called", "Pentest AI Planner Called"),
                ],
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="securewiserepository",
            name="access_mode",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("integration", "Integration"),
                    ("github_app", "GitHub App"),
                    ("local_path", "Local Path"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SecureWiseGitHubAppInstallation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("installation_id", models.PositiveBigIntegerField(unique=True)),
                ("account_id", models.PositiveBigIntegerField()),
                ("account_login", models.CharField(max_length=200)),
                ("account_type", models.CharField(blank=True, max_length=30)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_app_installations",
                        to="securewise.securewiseorganization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="securewiserepository",
            name="github_app_installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repositories",
                to="securewise.securewisegithubappinstallation",
            ),
        ),
        migrations.AddConstraint(
            model_name="securewiserepository",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_repository_id__isnull", False)),
                fields=("organization", "provider_repository_id"),
                name="sw_repo_org_provider_id_unique",
            ),
        ),
        migrations.AddField(
            model_name="securewisegithubappstate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="securewise.securewiseorganization"
            ),
        ),
        migrations.AddField(
            model_name="securewisegithubappstate",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name="securewisegithubappinstallation",
            constraint=models.UniqueConstraint(
                fields=("organization", "account_id"), name="sw_github_install_org_account_unique"
            ),
        ),
    ]
