"""Original teaching scenarios; no official exam material is reproduced."""

# topic, venue, audience, activity, rule, reason, exception, next action, trade-off
SCENARIOS = [
    (
        "bibliotheek",
        "de wijkbibliotheek",
        "leden van de bibliotheek",
        "boeken lenen",
        "boeken moeten binnen drie weken worden teruggebracht",
        "andere lezers moeten de boeken ook kunnen gebruiken",
        "een boek kan worden verlengd als niemand het heeft gereserveerd",
        "controleer de inleverdatum in uw account",
        "langere leentijden zijn prettig voor lezers, maar maken populaire boeken minder beschikbaar",
    ),
    (
        "wonen",
        "de woningcorporatie",
        "huurders",
        "een reparatie aanvragen",
        "gewone reparaties moeten via het bewonersportaal worden gemeld",
        "de medewerkers kunnen zo de volgorde van de meldingen volgen",
        "bij een gevaarlijke lekkage moet u direct het noodnummer bellen",
        "beschrijf het probleem en voeg een duidelijke foto toe",
        "een digitaal systeem is overzichtelijk, maar niet iedere huurder kan het zonder hulp gebruiken",
    ),
    (
        "werk",
        "het distributiecentrum",
        "medewerkers",
        "een dienst ruilen",
        "een ruil moet vooraf door de teamleider worden goedgekeurd",
        "op iedere dienst moeten genoeg mensen met de juiste ervaring aanwezig zijn",
        "bij ziekte belt de medewerker direct de leidinggevende",
        "bespreek de ruil eerst met uw collega en stuur daarna een verzoek",
        "flexibele werktijden helpen medewerkers, maar de bezetting mag daardoor niet onvoorspelbaar worden",
    ),
    (
        "opleiding",
        "het opleidingscentrum",
        "cursisten",
        "een avondcursus volgen",
        "cursisten moeten voor de eerste les hun inschrijving bevestigen",
        "het centrum moet weten hoeveel plaatsen nog vrij zijn",
        "wie op de wachtlijst staat, krijgt pas na een bericht een plaats",
        "bevestig de inschrijving via de link in de e-mail",
        "een vaste inschrijfdatum geeft duidelijkheid, maar laat weinig ruimte voor mensen met wisselende werktijden",
    ),
    (
        "gezondheid",
        "de huisartsenpraktijk",
        "patiënten",
        "een afspraak maken",
        "niet-dringende vragen worden op werkdagen met de assistent besproken",
        "de assistent kan bepalen welk soort afspraak nodig is",
        "bij een levensbedreigende situatie belt u 112",
        "houd uw gegevens en een korte beschrijving van uw klachten bij de hand",
        "een eerste beoordeling voorkomt onnodige afspraken, maar mag dringende hulp niet vertragen",
    ),
    (
        "vervoer",
        "de vervoerder",
        "reizigers",
        "een vervangende bus gebruiken",
        "reizigers moeten bij werkzaamheden de gele borden naar de tijdelijke halte volgen",
        "de gewone halte is tijdens de werkzaamheden niet veilig bereikbaar",
        "reizigers die assistentie nodig hebben, kunnen vooraf hulp aanvragen",
        "controleer vlak voor vertrek de actuele reisplanner",
        "werkzaamheden verbeteren de verbinding, maar veroorzaken tijdelijk langere reistijden",
    ),
    (
        "vrijwilligerswerk",
        "het buurthuis",
        "vrijwilligers",
        "helpen bij een buurtmaaltijd",
        "vrijwilligers melden voor de maaltijd welke taak zij kunnen doen",
        "de coördinator moet de voorbereiding en het opruimen verdelen",
        "nieuwe vrijwilligers mogen de eerste keer met een ervaren helper meelopen",
        "kies een taak en geef uw beschikbaarheid door",
        "een vast rooster verdeelt het werk eerlijk, maar moet ruimte laten voor onverwachte afmeldingen",
    ),
    (
        "gemeente",
        "het gemeenteloket",
        "inwoners",
        "een document aanvragen",
        "voor deze aanvraag is een afspraak en een geldig identiteitsbewijs nodig",
        "de medewerker moet de identiteit van de aanvrager controleren",
        "wie digitaal geen afspraak kan maken, kan het loket telefonisch bereiken",
        "lees welke documenten u moet meenemen voordat u vertrekt",
        "werken op afspraak vermindert wachttijden, maar toegang moet ook mogelijk blijven zonder digitale vaardigheden",
    ),
    (
        "kinderopvang",
        "het kinderdagverblijf",
        "ouders",
        "een extra opvangdag aanvragen",
        "een extra dag wordt alleen bevestigd wanneer er voldoende personeel en ruimte is",
        "de groep moet veilig en overzichtelijk blijven",
        "een aanvraag op de wachtlijst is nog geen bevestigde opvangdag",
        "wacht op de schriftelijke bevestiging voordat u uw planning verandert",
        "extra dagen helpen gezinnen, maar mogen de kwaliteit van de opvang niet verminderen",
    ),
    (
        "sport",
        "de sportvereniging",
        "sporters",
        "deelnemen aan een training",
        "deelnemers moeten zich vooraf voor een trainingsgroep aanmelden",
        "de trainer wil de oefeningen aan de grootte van de groep aanpassen",
        "een nieuwe deelnemer kan na overleg eerst een proeftraining volgen",
        "kies een passende groep en neem contact op met de trainer",
        "kleine groepen geven meer persoonlijke aandacht, maar bieden minder plaatsen",
    ),
    (
        "energie",
        "de energiecoöperatie",
        "buurtbewoners",
        "meedoen aan een bespaarproject",
        "deelnemers vergelijken hun verbruik met een vergelijkbare periode",
        "het weer en het aantal bewoners beïnvloeden het verbruik",
        "een lager maandbedrag betekent niet automatisch dat minder energie is gebruikt",
        "noteer de meterstanden en bespreek de resultaten met de adviseur",
        "besparing is belangrijk, maar een eenvoudige vergelijking kan misleidend zijn zonder context",
    ),
    (
        "afval",
        "het afvalpunt",
        "bewoners",
        "grof afval inleveren",
        "bewoners moeten verschillende soorten afval apart aanbieden",
        "gescheiden materiaal kan beter opnieuw worden gebruikt",
        "chemisch afval hoort niet bij gewone meubels of verpakkingen",
        "bekijk vooraf bij welk vak uw afval hoort",
        "meer aparte afvalstromen verbeteren hergebruik, maar vragen extra uitleg voor bezoekers",
    ),
    (
        "veiligheid",
        "de werkplaats",
        "stagiairs",
        "een machine gebruiken",
        "stagiairs mogen de machine pas na uitleg en onder toezicht gebruiken",
        "verkeerd gebruik kan letsel of schade veroorzaken",
        "bij een storing stopt iedereen direct en wordt de begeleider gewaarschuwd",
        "vraag de begeleider om de veiligheidsinstructie",
        "zorgvuldige uitleg kost tijd, maar voorkomt dat snelheid belangrijker wordt dan veiligheid",
    ),
    (
        "cultuur",
        "het cultuurcentrum",
        "bezoekers",
        "een voorstelling bijwonen",
        "bezoekers moeten hun reservering bij de ingang laten zien",
        "het aantal bezoekers mag het aantal beschikbare plaatsen niet overschrijden",
        "een bezoeker met een rolstoel kan vooraf een geschikte plaats aanvragen",
        "controleer de bevestiging en kom op tijd naar de ingang",
        "vaste plaatsen maken de toegang overzichtelijk, maar er moet rekening worden gehouden met toegankelijkheid",
    ),
    (
        "solliciteren",
        "het leerwerkbedrijf",
        "sollicitanten",
        "deelnemen aan een kennismakingsgesprek",
        "sollicitanten moeten voorbeelden van hun ervaring voorbereiden",
        "het gesprek gaat niet alleen over diploma's maar ook over praktische vaardigheden",
        "wie nog geen werkervaring heeft, mag voorbeelden uit opleiding of vrijwilligerswerk gebruiken",
        "kies twee voorbeelden die passen bij de functie",
        "standaardvragen maken kandidaten vergelijkbaar, maar kunnen bijzondere ervaring onvoldoende zichtbaar maken",
    ),
    (
        "geldzaken",
        "het budgetspreekuur",
        "inwoners met geldvragen",
        "een overzicht van uitgaven maken",
        "bezoekers brengen hun vaste lasten en recente inkomsten in kaart",
        "zonder volledig overzicht is het moeilijk om een haalbaar plan te maken",
        "wie een document mist, kan toch komen en later informatie aanvullen",
        "verzamel de beschikbare brieven en bankgegevens",
        "een volledig overzicht is nuttig, maar een strenge documentenlijst mag hulp niet blokkeren",
    ),
    (
        "zorgverlof",
        "de personeelsafdeling",
        "werknemers met zorgtaken",
        "verlof bespreken",
        "werknemers bespreken geplande afwezigheid tijdig met hun leidinggevende",
        "het team moet weten welke werkzaamheden moeten worden overgenomen",
        "bij een onverwachte noodsituatie meldt de werknemer zich zo snel mogelijk",
        "geef aan wanneer u afwezig verwacht te zijn zonder onnodige privégegevens te delen",
        "goede planning helpt het team, maar privacy en onverwachte zorgtaken verdienen ook aandacht",
    ),
    (
        "digitale_hulp",
        "het informatiepunt",
        "inwoners die digitale hulp zoeken",
        "een online formulier invullen",
        "de bezoeker voert zelf wachtwoorden en persoonlijke codes in",
        "de helper hoeft geen geheime gegevens te kennen",
        "zonder eigen apparaat kan de bezoeker een beveiligde computer op het informatiepunt gebruiken",
        "neem de brief met de uitleg mee en log na afloop uit",
        "persoonlijke hulp verlaagt drempels, maar mag geen afhankelijkheid of privacyrisico creëren",
    ),
    (
        "duurzaamheid",
        "de reparatiewerkplaats",
        "mensen met een kapot apparaat",
        "een apparaat laten onderzoeken",
        "vrijwilligers onderzoeken eerst of een reparatie veilig en haalbaar is",
        "niet ieder onderdeel kan zonder risico worden vervangen",
        "een apparaat met een beschadigde accu wordt niet ter plaatse gerepareerd",
        "beschrijf de storing en vraag welke vervolgstap mogelijk is",
        "repareren beperkt afval, maar niet elke reparatie is verantwoord",
    ),
    (
        "samenleven",
        "het bewonersoverleg",
        "bewoners van een flat",
        "afspraken over een gedeelde ruimte maken",
        "voorstellen worden besproken voordat een gezamenlijke beslissing wordt genomen",
        "de ruimte wordt door verschillende groepen gebruikt",
        "een urgente veiligheidsmaatregel hoeft niet op het volgende overleg te wachten",
        "stuur een concreet voorstel met een uitleg van de gevolgen",
        "een snel besluit is efficiënt, maar draagvlak vraagt dat ook minder zichtbare bewoners worden gehoord",
    ),
]

INTENT = {
    "bibliotheek": "de inleverdatum in mijn account controleren",
    "wonen": "het probleem beschrijven en een duidelijke foto toevoegen",
    "werk": "de ruil met mijn collega bespreken en een verzoek sturen",
    "opleiding": "mijn inschrijving bevestigen via de link in de e-mail",
    "gezondheid": "mijn gegevens en een korte beschrijving van mijn klachten voorbereiden",
    "vervoer": "vlak voor vertrek de actuele reisplanner controleren",
    "vrijwilligerswerk": "een taak kiezen en mijn beschikbaarheid doorgeven",
    "gemeente": "controleren welke documenten ik moet meenemen",
    "kinderopvang": "op de schriftelijke bevestiging wachten",
    "sport": "een passende groep kiezen en contact opnemen met de trainer",
    "energie": "de meterstanden noteren en de resultaten bespreken",
    "afval": "vooraf bekijken bij welk vak mijn afval hoort",
    "veiligheid": "de begeleider om de veiligheidsinstructie vragen",
    "cultuur": "de bevestiging controleren en op tijd komen",
    "solliciteren": "twee voorbeelden kiezen die passen bij de functie",
    "geldzaken": "de beschikbare brieven en bankgegevens verzamelen",
    "zorgverlof": "mijn verwachte afwezigheid tijdig doorgeven",
    "digitale_hulp": "de brief met uitleg meenemen en na afloop uitloggen",
    "duurzaamheid": "de storing beschrijven en vragen welke vervolgstap mogelijk is",
    "samenleven": "een concreet voorstel met een toelichting sturen",
}

# KNM facts are civic teaching material, not legal advice or copied exam items.
# topic, scenario, correct principle, two plausible misconceptions, explanation
CIVIC = [
    (
        "gezondheid",
        "U hebt een niet-dringende medische klacht.",
        "Neem contact op met uw huisarts.",
        "Bel altijd het alarmnummer 112.",
        "Ga alleen naar de gemeente.",
        "De huisarts is het gebruikelijke eerste aanspreekpunt bij niet-dringende medische klachten.",
    ),
    (
        "wonen",
        "Er is een gevaarlijke gaslucht in uw woning.",
        "Zoek veiligheid en waarschuw de juiste hulpdienst.",
        "Wacht tot de volgende huurbetaling.",
        "Steek een lucifer aan om de bron te zoeken.",
        "Een mogelijke gaslekkage vraagt veilige en directe actie, niet uitstel of een vlam.",
    ),
    (
        "werk",
        "U krijgt een arbeidsovereenkomst aangeboden.",
        "Lees de afspraken voordat u ondertekent.",
        "Een mondeling salarisbedrag vervangt alle voorwaarden.",
        "U hoeft afspraken over werktijden niet te bekijken.",
        "Een overeenkomst bevat belangrijke afspraken over onder andere werk, uren en beloning.",
    ),
    (
        "onderwijs",
        "Een ouder begrijpt een bericht van de school niet.",
        "Vraag de school om uitleg.",
        "Houd het kind zonder overleg thuis.",
        "Neem aan dat de school geen contact wil.",
        "Ouders en school kunnen vragen bespreken; onduidelijkheid is een reden om contact te zoeken.",
    ),
    (
        "democratie",
        "Iemand wil invloed hebben op gemeentelijke plannen.",
        "Informeer naar inspraak en openbare vergaderingen.",
        "Alleen de politie bespreekt nieuwe plannen.",
        "Inwoners mogen nooit reageren op plannen.",
        "Gemeenten bieden mogelijkheden om informatie te krijgen en op plannen te reageren.",
    ),
    (
        "gelijkheid",
        "Een collega heeft een andere godsdienst dan u.",
        "Respecteer de collega en gelijke behandeling.",
        "Een andere godsdienst is een reden om iemand uit te sluiten.",
        "Alle collega's moeten hetzelfde geloven.",
        "Gelijke behandeling en vrijheid van godsdienst zijn belangrijke uitgangspunten.",
    ),
    (
        "geld",
        "U kunt een rekening waarschijnlijk niet op tijd betalen.",
        "Neem tijdig contact op en vraag welke oplossing mogelijk is.",
        "Negeer alle brieven totdat de schuld verdwijnt.",
        "Een aanmaning betekent dat betalen nooit meer nodig is.",
        "Vroeg contact kan helpen problemen te bespreken; negeren lost de rekening niet op.",
    ),
    (
        "veiligheid",
        "U ziet een levensbedreigende noodsituatie.",
        "Bel 112 als directe hulp nodig is.",
        "Wacht eerst op een gewone gemeentelijke afspraak.",
        "Stuur alleen een bericht naar uw werkgever.",
        "112 is bedoeld voor situaties waarin met spoed hulp nodig is.",
    ),
    (
        "gemeente",
        "U verhuist naar een andere gemeente.",
        "Controleer hoe u uw nieuwe adres bij de gemeente doorgeeft.",
        "Een verhuizing hoeft nooit te worden gemeld.",
        "Alleen uw supermarkt houdt uw officiële adres bij.",
        "De gemeente beheert de registratie van inwoners; controleer de procedure voor uw situatie.",
    ),
    (
        "verzekeren",
        "U wilt weten welke zorgverzekering bij uw situatie past.",
        "Controleer de voorwaarden en vergelijk passende verzekeringen.",
        "Iedere verzekering heeft altijd dezelfde voorwaarden.",
        "Een verzekering dekt zonder uitzondering iedere uitgave.",
        "Premies, voorwaarden en dekking moeten worden nagekeken; niet iedere uitgave wordt automatisch vergoed.",
    ),
    (
        "vrijwilligerswerk",
        "U wilt helpen in uw buurt.",
        "Vraag een organisatie welke vrijwilligerstaak beschikbaar is.",
        "Vrijwilligerswerk kan alleen via een betaald arbeidscontract.",
        "Buurtorganisaties mogen geen hulp vragen.",
        "Vrijwilligerswerk kan een manier zijn om bij te dragen en contacten op te bouwen.",
    ),
    (
        "afval",
        "U hebt lege batterijen.",
        "Lever ze in bij een geschikt inzamelpunt.",
        "Leg ze altijd bij etensresten.",
        "Gooi ze in een sloot omdat ze klein zijn.",
        "Batterijen worden apart ingezameld; ze horen niet in voedselafval of het milieu.",
    ),
    (
        "privacy",
        "Een onbekende vraagt via een bericht om uw inlogcode.",
        "Deel de code niet en controleer het bericht via een betrouwbaar kanaal.",
        "Deel de code zodra het bericht dringend klinkt.",
        "Een logo bewijst altijd dat de afzender betrouwbaar is.",
        "Geheime codes blijven privé; urgentie of een logo bewijst niet dat een bericht echt is.",
    ),
    (
        "solliciteren",
        "U zoekt werk en wilt een werkgever benaderen.",
        "Leg uit welke ervaring en vaardigheden bij de functie passen.",
        "Vertel alleen welke hobby uw buurman heeft.",
        "Een sollicitatie mag geen informatie over uw vaardigheden bevatten.",
        "Een werkgever moet kunnen begrijpen waarom uw vaardigheden bij de functie passen.",
    ),
    (
        "taal",
        "U wilt beter Nederlands leren.",
        "Zoek passende lessen en oefen in dagelijkse situaties.",
        "Alleen een identiteitsbewijs zorgt dat uw taalniveau stijgt.",
        "Oefenen kan nooit helpen bij taal leren.",
        "Lessen en regelmatig oefenen kunnen de taalvaardigheid ondersteunen.",
    ),
    (
        "discriminatie",
        "U denkt dat u ongelijk wordt behandeld vanwege uw afkomst.",
        "Zoek informatie en meld het bij een passende instantie.",
        "Ongelijke behandeling vanwege afkomst is altijd toegestaan.",
        "Er bestaat geen mogelijkheid om advies te vragen.",
        "Discriminatie is niet vanzelfsprekend toegestaan; u kunt advies en ondersteuning zoeken.",
    ),
    (
        "verkeer",
        "U steekt een drukke weg over.",
        "Controleer het verkeer en volg de verkeerslichten.",
        "Een rood voetgangerslicht betekent altijd dat u voorrang hebt.",
        "Kijk alleen naar uw telefoon.",
        "Veilig oversteken vraagt aandacht voor verkeer en geldende signalen.",
    ),
    (
        "rechten",
        "U krijgt een besluit van een overheidsinstantie dat u niet begrijpt.",
        "Lees de uitleg en informeer naar de beschikbare vervolgstappen.",
        "Een besluit kan nooit uitleg of een reactietermijn bevatten.",
        "Gooi de brief weg zodat het besluit verdwijnt.",
        "Een besluit kan uitleg en een termijn voor reactie bevatten; controleer de brief of vraag hulp.",
    ),
    (
        "participatie",
        "U kent weinig mensen in uw nieuwe woonplaats.",
        "U kunt deelnemen aan een buurtactiviteit.",
        "Buurtactiviteiten zijn altijd verboden voor nieuwe inwoners.",
        "Contact is alleen mogelijk via een belastingaangifte.",
        "Een buurtactiviteit kan gelegenheid bieden om andere inwoners te ontmoeten.",
    ),
    (
        "gezinsleven",
        "Een ouder zoekt informatie over opvang.",
        "Vraag naar de voorwaarden, kosten en beschikbare plaatsen.",
        "Iedere opvangplaats is zonder afspraken altijd gratis.",
        "Beschikbare plaatsen hoeven nooit te worden bevestigd.",
        "Opvang vraagt duidelijke informatie over beschikbaarheid, afspraken en kosten.",
    ),
    (
        "onderwijs",
        "Een kind is ziek en kan niet naar school.",
        "Meld de afwezigheid volgens de afspraak met de school.",
        "Laat de school zonder bericht wachten.",
        "Een ziektebericht kan alleen bij de bank worden gedaan.",
        "De school moet weten waarom een leerling afwezig is.",
    ),
    (
        "werk",
        "U bent ziek op een dag waarop u zou werken.",
        "Meld u ziek volgens de afspraken van uw werkgever.",
        "Wacht zonder bericht tot de volgende salarisbetaling.",
        "Laat alleen een klant weten dat u niet komt.",
        "Bij ziekte volgt u de ziekmeldprocedure die voor uw werk geldt.",
    ),
    (
        "geld",
        "U krijgt een loonstrook met een onbekende inhouding.",
        "Vraag uw werkgever om uitleg over de loonstrook.",
        "Elke onbekende inhouding betekent automatisch fraude.",
        "Een loonstrook mag nooit worden besproken.",
        "Vraag uitleg voordat u conclusies trekt over een inhouding.",
    ),
    (
        "zorg",
        "Uw arts noemt een behandeling die u niet begrijpt.",
        "Vraag uitleg over de behandeling en de mogelijke gevolgen.",
        "U mag nooit vragen stellen aan een arts.",
        "Een handtekening betekent dat uitleg overbodig is.",
        "U kunt vragen stellen om een geïnformeerde beslissing te nemen.",
    ),
    (
        "wonen",
        "U huurt een woning en wilt weten wat is afgesproken.",
        "Lees het huurcontract en vraag uitleg over onduidelijke onderdelen.",
        "Alle huurafspraken staan uitsluitend op een kassabon.",
        "Een huurcontract kan geen afspraken bevatten.",
        "Het huurcontract beschrijft belangrijke afspraken; onduidelijkheden kunt u bespreken.",
    ),
    (
        "democratie",
        "U krijgt een stempas voor een verkiezing.",
        "Lees waar, wanneer en onder welke voorwaarden u kunt stemmen.",
        "U moet stemmen op de partij die uw werkgever kiest.",
        "De stempas is een verplichte betalingsopdracht.",
        "Een kiezer maakt een eigen keuze; de stempas geeft praktische informatie.",
    ),
    (
        "vrijheid",
        "U bent het niet eens met de mening van uw buur.",
        "U kunt respectvol uw eigen mening geven.",
        "Een meningsverschil geeft recht om de buur te bedreigen.",
        "Iedereen moet dezelfde mening hebben.",
        "Vrijheid van meningsuiting betekent niet dat bedreiging is toegestaan.",
    ),
    (
        "recht",
        "U wordt gevraagd een contract te tekenen dat u niet begrijpt.",
        "Vraag uitleg of passend advies voordat u tekent.",
        "Onbegrijpelijke tekst verplicht u direct te tekenen.",
        "Een contract heeft nooit gevolgen.",
        "U moet kunnen begrijpen welke afspraken en gevolgen een contract heeft.",
    ),
    (
        "veiligheid",
        "U vermoedt een niet-dringende online oplichting.",
        "Bewaar relevante informatie en vraag advies bij een passende instantie.",
        "Betaal extra geld zodat de afzender stopt.",
        "Deel onmiddellijk meer wachtwoorden.",
        "Bewaar informatie en gebruik betrouwbare hulpkanalen; geef geen extra geheime gegevens.",
    ),
    (
        "verkeer",
        "U wilt in Nederland gaan autorijden.",
        "Controleer of uw rijbewijs hier geldig is.",
        "Elk buitenlands rijbewijs blijft in elke situatie onbeperkt geldig.",
        "Een buskaart vervangt een rijbewijs.",
        "De geldigheid hangt af van uw situatie; controleer de regels bij een betrouwbare instantie.",
    ),
    (
        "belasting",
        "U krijgt een officiële belastingbrief.",
        "Lees de brief en controleer welke actie en termijn worden genoemd.",
        "Negeer elke termijn omdat de brief officieel is.",
        "Betaal zonder controle aan een onbekende link.",
        "Controleer de brief via een betrouwbaar kanaal en let op de gevraagde actie.",
    ),
    (
        "pensioen",
        "U wilt weten welke pensioenafspraken bij uw werk horen.",
        "Vraag informatie over de regeling die voor u geldt.",
        "Iedere werkgever heeft zonder uitzondering dezelfde regeling.",
        "Pensioeninformatie is altijd geheim voor de werknemer.",
        "Pensioenregelingen kunnen verschillen; vraag informatie over uw eigen situatie.",
    ),
    (
        "zorgverzekering",
        "U krijgt een rekening voor zorg.",
        "Controleer de rekening en uw verzekeringsvoorwaarden.",
        "Iedere zorgrekening is automatisch onjuist.",
        "Een zorgverzekering vergoedt altijd alles zonder voorwaarden.",
        "Dekking en eventuele eigen kosten hangen af van de behandeling en voorwaarden.",
    ),
    (
        "contact",
        "Een organisatie nodigt u uit voor een afspraak die niet past.",
        "Neem tijdig contact op om te bespreken of verzetten mogelijk is.",
        "Kom zonder bericht op een willekeurige andere dag.",
        "De uitnodiging hoeft nooit te worden gelezen.",
        "Contact opnemen helpt duidelijke afspraken te maken.",
    ),
    (
        "taalhulp",
        "U kunt een belangrijk formulier niet goed lezen.",
        "Vraag hulp bij een betrouwbaar informatiepunt.",
        "Deel al uw geheime codes met de eerste onbekende.",
        "Een ongelezen formulier heeft nooit betekenis.",
        "Vraag passende hulp, maar houd geheime gegevens privé.",
    ),
    (
        "milieu",
        "U wilt een kapot apparaat wegdoen.",
        "Controleer of reparatie of een geschikt inzamelpunt mogelijk is.",
        "Leg elk apparaat in de natuur.",
        "Een batterij moet altijd worden verbrand.",
        "Reparatie en passende inzameling beperken afval en risico's.",
    ),
    (
        "werkveiligheid",
        "U weet niet hoe u een machine veilig gebruikt.",
        "Vraag instructies voordat u ermee begint.",
        "Begin direct, ook zonder veiligheidskennis.",
        "Verwijder eerst de beveiliging van de machine.",
        "Veilige instructie helpt ongelukken te voorkomen.",
    ),
    (
        "opvang",
        "Uw kind heeft een ernstige allergie en gaat naar opvang.",
        "Bespreek de allergie en benodigde afspraken met de opvang.",
        "Houd deze informatie altijd geheim voor de begeleiders.",
        "Ga ervan uit dat begeleiders de allergie vanzelf kennen.",
        "Begeleiders hebben relevante informatie nodig om veilige afspraken te maken.",
    ),
    (
        "gemeenteraad",
        "U wilt weten wie lokale besluiten bespreekt.",
        "Bekijk informatie over de gemeenteraad en het gemeentebestuur.",
        "Alle lokale besluiten worden door uw huisarts genomen.",
        "Een verhuurder vervangt altijd de gemeenteraad.",
        "De gemeenteraad en het gemeentebestuur hebben rollen in lokale besluitvorming.",
    ),
    (
        "participatie",
        "U wilt deelnemen aan een cursus maar twijfelt over de voorwaarden.",
        "Vraag de aanbieder naar toegang, kosten en ondersteuning.",
        "Een cursus heeft zonder uitzondering geen voorwaarden.",
        "U moet eerst ongevraagd een wachtwoord opsturen.",
        "Concrete informatie helpt bepalen of een cursus bij uw situatie past.",
    ),
]

# Misconceptions tied to the situation, rather than unrelated joke answers.
CIVIC_DISTRACTORS = [
    (
        "Ga zonder overleg direct naar de spoedeisende hulp.",
        "Wacht uitsluitend op de volgende afspraak met de gemeente.",
    ),
    ("Wacht binnen op de gewone reparatiedienst van volgende week.", "Zoek de lekkage zelf met een open vlam."),
    (
        "Onderteken eerst en lees de voorwaarden pas na uw eerste werkdag.",
        "Bekijk alleen het salaris en sla de overige afspraken over.",
    ),
    ("Wacht zonder contact tot het volgende schoolrapport.", "Neem aan dat het bericht niet voor uw gezin bedoeld is."),
    (
        "Wacht tot de plannen zijn uitgevoerd voordat u informatie zoekt.",
        "Vraag uitsluitend uw werkgever om de plannen namens de gemeente te wijzigen.",
    ),
    (
        "Vraag de collega op het werk zijn godsdienst af te zweren.",
        "Sluit de collega uit van gezamenlijke taken vanwege de godsdienst.",
    ),
    (
        "Wacht zonder contact tot er meerdere aanmaningen zijn.",
        "Ga ervan uit dat een rekening vervalt als u niet reageert.",
    ),
    (
        "Vraag eerst een gewone afspraak bij het gemeenteloket.",
        "Wacht tot de volgende werkdag om medische hulp te zoeken.",
    ),
    (
        "Geef het nieuwe adres alleen aan de verhuurder door.",
        "Wacht zonder controle tot de oude gemeente het adres vanzelf aanpast.",
    ),
    (
        "Kies zonder voorwaarden te lezen de laagste maandpremie.",
        "Neem aan dat iedere behandeling door iedere polis volledig wordt vergoed.",
    ),
    (
        "Wacht op een betaald contract voordat u een vrijwilligerstaak bespreekt.",
        "Begin zonder overleg een taak op een plek waar u nog niet bent ingedeeld.",
    ),
    ("Doe ze bij de gewone etensresten.", "Bewaar ze los bij een warmtebron totdat ze gaan lekken."),
    (
        "Stuur de code als de afzender een bekend logo gebruikt.",
        "Geef de code omdat het bericht zegt dat u snel moet reageren.",
    ),
    (
        "Stuur dezelfde tekst zonder naar de functie te kijken.",
        "Laat relevante ervaring weg om het bericht zo kort mogelijk te maken.",
    ),
    (
        "Stop met oefenen zodra u bij een cursus bent ingeschreven.",
        "Oefen alleen woorden die u al zonder moeite begrijpt.",
    ),
    (
        "Neem aan dat dit altijd is toegestaan en vraag geen advies.",
        "Reageer uitsluitend met een bedreiging zonder hulp of informatie te zoeken.",
    ),
    (
        "Steek bij rood over omdat andere voetgangers ook lopen.",
        "Kijk vooral op uw telefoon en vertrouw op het geluid van auto's.",
    ),
    (
        "Wacht zonder de brief te lezen tot elke reactietermijn voorbij is.",
        "Ga ervan uit dat vragen stellen het besluit automatisch ongedaan maakt.",
    ),
    (
        "Wacht af zonder mogelijke activiteiten te bekijken.",
        "Neem aan dat nieuwe bewoners niet aan bestaande activiteiten mogen meedoen.",
    ),
    (
        "Maak uw werkplanning zonder bevestiging van een opvangplaats.",
        "Neem aan dat alle opvang zonder voorwaarden gratis is.",
    ),
    (
        "Stuur zonder overleg geen bericht en verwacht dat de school het weet.",
        "Meld de afwezigheid pas bij de volgende ouderavond.",
    ),
    ("Informeer alleen een klant, niet uw werkgever.", "Wacht tot u beter bent voordat u uw afwezigheid meldt."),
    (
        "Neem zonder uitleg aan dat de inhouding altijd een fout is.",
        "Onderteken ongezien een verklaring dat u iedere inhouding accepteert.",
    ),
    (
        "Stem toe zonder te vragen wat de behandeling betekent.",
        "Veronderstel dat u als patiënt geen vragen mag stellen.",
    ),
    (
        "Vertrouw alleen op wat een vorige huurder zich herinnert.",
        "Onderteken wijzigingen zonder de nieuwe afspraken te lezen.",
    ),
    ("Laat uw werkgever verplicht bepalen op welke partij u stemt.", "Betaal de stempas alsof het een factuur is."),
    (
        "Probeer de buur met bedreiging tot dezelfde mening te dwingen.",
        "Veronderstel dat u uw eigen mening nooit mag uitspreken.",
    ),
    ("Teken direct omdat de andere partij haast heeft.", "Vertrouw erop dat ondertekenen nooit verplichtingen geeft."),
    (
        "Betaal opnieuw om het eerdere bedrag terug te krijgen zonder controle.",
        "Deel extra inloggegevens om uw identiteit bij de onbekende te bewijzen.",
    ),
    (
        "Neem zonder controle aan dat de regels voor ieder buitenlands rijbewijs hetzelfde zijn.",
        "Begin alvast te rijden en controleer de geldigheid pas later.",
    ),
    (
        "Betaal via een onbekende link zonder het bericht te controleren.",
        "Leg de brief weg zonder de termijn te bekijken.",
    ),
    (
        "Neem aan dat uw regeling gelijk is aan die van iedere andere werkgever.",
        "Wacht met informatie zoeken tot u met pensioen gaat.",
    ),
    (
        "Neem aan dat elke ontvangen rekening volledig wordt vergoed.",
        "Betaal een onduidelijk bedrag zonder de rekening of voorwaarden te controleren.",
    ),
    (
        "Verschijn zonder overleg op een andere dag.",
        "Laat de uitnodiging onbeantwoord en verwacht automatisch een nieuwe datum.",
    ),
    (
        "Stuur alle persoonlijke codes mee aan een onbekende die hulp aanbiedt.",
        "Onderteken het formulier zonder de inhoud te begrijpen.",
    ),
    (
        "Doe ieder elektrisch apparaat bij het gewone restafval zonder controle.",
        "Vervang de accu zelf zonder te weten of dat veilig is.",
    ),
    (
        "Begin zonder uitleg en vraag pas hulp bij een probleem.",
        "Verwijder de beveiliging om de machine sneller te gebruiken.",
    ),
    (
        "Wacht met melden totdat er bij de opvang een reactie ontstaat.",
        "Veronderstel dat iedere begeleider de allergie al kent.",
    ),
    (
        "Vraag uitsluitend de verhuurder wie alle gemeentelijke besluiten neemt.",
        "Neem aan dat gemeentelijke vergaderingen nooit informatie voor inwoners bevatten.",
    ),
    (
        "Meld u aan zonder kosten of toegangseisen te bekijken.",
        "Neem aan dat ondersteuning bij alle aanbieders identiek is.",
    ),
]

CIVIC.extend(
    [
        (
            "geografie",
            "Een bezoeker vraagt welke stad de hoofdstad is en waar de regering werkt.",
            "Amsterdam is de hoofdstad; de regering werkt in Den Haag.",
            "",
            "",
            "De hoofdstad en de vestigingsplaats van de regering zijn niet dezelfde stad.",
        ),
        (
            "geografie",
            "U bekijkt een kaart van Nederland en zoekt de regionale bestuursgebieden.",
            "Bekijk de provincies op de kaart.",
            "",
            "",
            "Nederland is verdeeld in provincies; gemeenten vormen een ander bestuursniveau.",
        ),
        (
            "geschiedenis",
            "Uw buurt organiseert een activiteit op 4 mei en een feest op 5 mei.",
            "Op 4 mei worden oorlogsslachtoffers herdacht; op 5 mei wordt de bevrijding gevierd.",
            "",
            "",
            "Dodenherdenking en Bevrijdingsdag hebben verschillende doelen.",
        ),
        (
            "geschiedenis",
            "Een museum vertelt over Nederland tijdens de Tweede Wereldoorlog.",
            "Nederland werd in de Tweede Wereldoorlog bezet en in 1945 bevrijd.",
            "",
            "",
            "De Duitse bezetting en de bevrijding in 1945 horen bij deze periode.",
        ),
        (
            "geografie",
            "U wilt naar een cursus in een andere stad en zoekt een openbaarvervoerverbinding.",
            "Gebruik een reisplanner en controleer de passende vervoersbewijzen.",
            "",
            "",
            "Een reisplanner en informatie over vervoersbewijzen helpen een reis zelfstandig voor te bereiden.",
        ),
        (
            "energie",
            "U verhuist en wilt weten hoe u gas of elektriciteit voor de woning regelt.",
            "Controleer welke leverancier en afspraken bij uw woning nodig zijn.",
            "",
            "",
            "Bij een verhuizing moet duidelijk zijn hoe nutsvoorzieningen worden geregeld.",
        ),
        (
            "rechtsstaat",
            "Iemand vraagt waarom een rechter onafhankelijk van een minister een zaak beoordeelt.",
            "De rechterlijke macht heeft een eigen taak, gescheiden van de uitvoerende macht.",
            "",
            "",
            "Scheiding van machten helpt voorkomen dat één partij alle overheidsmacht uitoefent.",
        ),
    ]
)
CIVIC_DISTRACTORS.extend(
    [
        (
            "Den Haag is de hoofdstad; de regering werkt in Amsterdam.",
            "Rotterdam is de hoofdstad en de regering werkt daar ook.",
        ),
        ("Zoek alleen de namen van woonstraten.", "Neem aan dat iedere stad een afzonderlijke provincie is."),
        (
            "Op 4 mei wordt Bevrijdingsdag gevierd en op 5 mei is Dodenherdenking.",
            "Beide dagen zijn uitsluitend bedoeld als nieuwjaarsviering.",
        ),
        (
            "Nederland werd in 1945 voor het eerst een provincie.",
            "De Tweede Wereldoorlog begon in Nederland pas na 1945.",
        ),
        (
            "Neem aan dat ieder vervoersbewijs op iedere verbinding geldig is.",
            "Gebruik uitsluitend een oud vertrektijdstip zonder actuele informatie te controleren.",
        ),
        (
            "Neem aan dat de leverancier zonder controle altijd gelijk blijft.",
            "Wacht zonder afspraken totdat alle voorzieningen worden afgesloten.",
        ),
        (
            "De minister bepaalt in iedere zaak persoonlijk de uitspraak.",
            "Alleen een verkiezingsuitslag bepaalt of iemand in een rechtszaak gelijk krijgt.",
        ),
    ]
)

KNM_THEMES = {
    "werk_inkomen": [2, 13, 21, 22, 31, 36],
    "omgang_waarden_normen": [5, 10, 14, 18, 26],
    "wonen": [1, 11, 24, 35, 45],
    "gezondheid_zorg": [0, 7, 9, 23, 32],
    "geschiedenis_geografie": [40, 41, 42, 43, 44],
    "instanties": [8, 12, 17, 27, 28, 29, 30, 33, 34],
    "staatsinrichting_rechtsstaat": [4, 15, 25, 38, 46],
    "onderwijs_opvoeding": [3, 19, 20, 37, 39],
}
