# Generated by Django 5.1.15 on 2026-09-30 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutch_practice', '0002_initial_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('content', models.BinaryField()),
                ('mime_type', models.CharField(default='video/mp4', max_length=40)),
                ('sha256', models.CharField(max_length=64)),
                ('duration_seconds', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dutch_practice.practicemedia'),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dutch_practice.practicemedia'),
        ),
    ]
