# Generated by Django 5.1.15 on 2026-09-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutch_practice', '0004_initial_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceattempt',
            name='skill',
            field=models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('knm', 'Knm')], max_length=10),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='skill',
            field=models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('knm', 'Knm')], max_length=10),
        ),
    ]
