# Generated by Django 5.1.15 on 2026-10-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dutch_practice", "0006_expanded_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptquestion",
            name="media_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practiceattempt",
            name="bank_version",
            field=models.CharField(default="legacy-v2", max_length=40),
        ),
        migrations.AddField(
            model_name="practiceattempt",
            name="blueprint",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="practiceattempt",
            name="last_position",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="practiceattempt",
            name="mode",
            field=models.CharField(
                choices=[("practice", "Practice"), ("mock", "Mock")], default="practice", max_length=10
            ),
        ),
    ]
