# Generated by Django 5.1.15 on 2026-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_wise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderattachment',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminderattachment',
            name='storage_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='reminderattachment',
            name='s3_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
