# Generated by Django 5.1.15 on 2026-05-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("future_wise", "0002_reminderattachment_db_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailreminder",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("future_self", "Letter to Future Self"),
                    ("milestone", "Open When… (Milestone)"),
                    ("grief", "In Memory — Grief Letter"),
                    ("forgiveness", "Forgiveness Letter"),
                    ("gratitude", "Gratitude Letter"),
                ],
                db_index=True,
                default="future_self",
                max_length=20,
            ),
        ),
    ]
