# Generated by Django 5.1.15 on 2026-05-31 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("future_wise", "0003_add_letter_type_to_emailreminder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "provider_class",
                    models.CharField(help_text="Dotted Python path to the IReminderProvider subclass.", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="emailreminder",
            name="channels_requested",
            field=models.CharField(
                default="email", help_text="Comma-separated channel codes e.g. 'email,sms,telegram'.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="emailreminder",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="E.164 format e.g. +447700900123. Required for SMS/Voice/WhatsApp channels.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emailreminder",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, default="", help_text="Obtained when user sends /start to the Telegram bot.", max_length=50
            ),
        ),
        migrations.CreateModel(
            name="ReminderDeliveryLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (channel unavailable or not requested)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("provider_response", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_logs",
                        to="future_wise.reminderchannel",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="future_wise.emailreminder",
                    ),
                ),
            ],
            options={
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(fields=["reminder", "channel", "attempt_number"], name="fw_log_reminder_ch_idx"),
                    models.Index(fields=["reminder", "status"], name="fw_log_reminder_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("is_opted_in", models.BooleanField(default=False)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default="", help_text="E.164 format e.g. +447700900123", max_length=20
                    ),
                ),
                ("telegram_chat_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "whatsapp_opted_in",
                    models.BooleanField(
                        default=False, help_text="True only after user sends the Twilio Sandbox join phrase."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_preferences",
                        to="future_wise.reminderchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["email", "channel__code"],
                "indexes": [models.Index(fields=["email", "channel"], name="fw_notifpref_email_ch_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("email", "channel"), name="fw_notifpref_email_channel_unique")
                ],
            },
        ),
    ]
