# Generated by Django 5.1.15 on 2026-06-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("future_wise", "0006_encrypt_subject_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailreminder",
            name="email",
            field=models.EmailField(blank=True, db_index=True, default="", max_length=254),
        ),
    ]
