# Generated by Django 5.1.15 on 2026-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("future_wise", "0008_emailreminder_channels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailreminder",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("future_self", "Letter to Future Self"),
                    ("milestone", "Open When… (Milestone)"),
                    ("grief", "In Memory — Grief Letter"),
                    ("forgiveness", "Forgiveness Letter"),
                    ("gratitude", "Gratitude Letter"),
                    ("general_reminder", "General Reminder"),
                    ("appointment_reminder", "Appointment Reminder"),
                    ("medicine_reminder", "Medicine Reminder"),
                    ("bill_payment_reminder", "Bill Payment Reminder"),
                    ("birthday_wish", "Birthday Wish"),
                    ("anniversary_wish", "Anniversary Wish"),
                    ("wedding_anniversary_wish", "Wedding Anniversary Wish"),
                    ("festival_wish", "Festival Wish"),
                    ("holiday_greeting", "Holiday Greeting"),
                    ("thank_you_message", "Thank You Message"),
                    ("congratulations_message", "Congratulations Message"),
                    ("get_well_soon_message", "Get Well Soon Message"),
                    ("meeting_reminder", "Meeting Reminder"),
                    ("school_event_reminder", "School Event Reminder"),
                    ("travel_reminder", "Travel Reminder"),
                    ("subscription_renewal_reminder", "Subscription Renewal Reminder"),
                    ("custom_message", "Custom Message"),
                ],
                db_index=True,
                default="future_self",
                max_length=40,
            ),
        ),
    ]
