# Generated by Django 5.1.15 on 2026-06-11 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('resumes', '0006_anonymousresumeidentity_resume_edit_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='anonymous_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_files', to='resumes.anonymousresumeidentity'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
